"""add new column

Revision ID: 047afacbce3c
Revises: f168692c65f2
Create Date: 2026-07-18 09:43:27.854019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '047afacbce3c'
down_revision: Union[str, Sequence[str], None] = 'f168692c65f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fs_balance_sheet_type_one', sa.Column('is_load_to_qdrant', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fs_balance_sheet_type_one', 'is_load_to_qdrant')
    # ### end Alembic commands ###
