"""create new column

Revision ID: 15b2d9d58a30
Revises: 3f9ad2c26465
Create Date: 2026-07-17 14:57:10.851441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15b2d9d58a30'
down_revision: Union[str, Sequence[str], None] = '3f9ad2c26465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'stock_price',
        sa.Column(
            'is_load_to_qdrant',
            sa.Integer(),
            nullable=False,
            server_default=sa.text('0'),
        ),
    )
    op.alter_column('stock_price', 'is_load_to_qdrant', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_price', 'is_load_to_qdrant')
    # ### end Alembic commands ###
