"""create newspapper table

Revision ID: 1a66fcdac06c
Revises: bd322b2acd17
Create Date: 2026-05-27 20:43:49.470441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a66fcdac06c'
down_revision: Union[str, Sequence[str], None] = 'bd322b2acd17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    existing_columns = {
        col["name"] for col in inspector.get_columns("fs_balance_sheet_type_four")
    }

    derivative_old = "derivative_financial_instruments_and_other_financial_liabilitie"
    derivative_new = "derivative_financial_instr_other_fin_liab"
    if derivative_new not in existing_columns:
        if derivative_old in existing_columns:
            op.alter_column(
                "fs_balance_sheet_type_four",
                derivative_old,
                new_column_name=derivative_new,
                existing_type=sa.INTEGER(),
                existing_nullable=False,
                existing_comment="IV. Các công cụ tài chính phái sinh và các khoản nợ tài chính khác",
                comment="IV. Các công cụ tài chính phái sinh và các khoản nợ tài chính khác",
            )
        else:
            op.add_column(
                "fs_balance_sheet_type_four",
                sa.Column(
                    derivative_new,
                    sa.Integer(),
                    nullable=False,
                    comment="IV. Các công cụ tài chính phái sinh và các khoản nợ tài chính khác",
                ),
            )

    grants_old = "grants_trusted_funds_and_borrowings_with_risks_borne_by_the_ban"
    grants_new = "grants_trusted_funds_borrowings_risk_borne_bank"
    if grants_new not in existing_columns:
        if grants_old in existing_columns:
            op.alter_column(
                "fs_balance_sheet_type_four",
                grants_old,
                new_column_name=grants_new,
                existing_type=sa.INTEGER(),
                existing_nullable=False,
                existing_comment="V. Vốn tài trợ, uỷ thác đầu tư mà ngân hàng chịu rủi ro",
                comment="V. Vốn tài trợ, uỷ thác đầu tư mà ngân hàng chịu rủi ro",
            )
        else:
            op.add_column(
                "fs_balance_sheet_type_four",
                sa.Column(
                    grants_new,
                    sa.Integer(),
                    nullable=False,
                    comment="V. Vốn tài trợ, uỷ thác đầu tư mà ngân hàng chịu rủi ro",
                ),
            )
    op.alter_column('fs_balance_sheet_type_four', 'total_placements_with_and_loans_to_other_cis',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='IV. Tiền, vàng gửi tại các TCTD khác và cho vay các TCTD khác',
               existing_nullable=False)
    op.alter_column('fs_balance_sheet_type_four', 'placements_with_other_credit_institutions',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='1. Tiền, Vàng gửi tại các TCTD khác',
               existing_nullable=False)
    op.alter_column('fs_balance_sheet_type_four', 'total_loans_to_customers',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='VII. Cho vay khách hàng',
               existing_nullable=False)
    op.alter_column('fs_balance_sheet_type_four', 'loans_to_customers_gross',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='1. Cho vay khách hàng',
               existing_nullable=False)
    op.alter_column('fs_balance_sheet_type_four', 'total_assets',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='TỔNG CỘNG TÀI SẢN',
               existing_nullable=False)
    op.alter_column('fs_balance_sheet_type_four', 'total_liabilities_and_equity',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='TỔNG CỘNG NGUỒN VỐN',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    existing_columns = {
        col["name"] for col in inspector.get_columns("fs_balance_sheet_type_four")
    }

    derivative_old = "derivative_financial_instruments_and_other_financial_liabilitie"
    derivative_new = "derivative_financial_instr_other_fin_liab"
    if derivative_old not in existing_columns:
        if derivative_new in existing_columns:
            op.alter_column(
                "fs_balance_sheet_type_four",
                derivative_new,
                new_column_name=derivative_old,
                existing_type=sa.INTEGER(),
                existing_nullable=False,
                existing_comment="IV. Các công cụ tài chính phái sinh và các khoản nợ tài chính khác",
                comment="IV. Các công cụ tài chính phái sinh và các khoản nợ tài chính khác",
            )
        else:
            op.add_column(
                "fs_balance_sheet_type_four",
                sa.Column(
                    derivative_old,
                    sa.INTEGER(),
                    autoincrement=False,
                    nullable=False,
                    comment="IV. Các công cụ tài chính phái sinh và các khoản nợ tài chính khác",
                ),
            )

    grants_old = "grants_trusted_funds_and_borrowings_with_risks_borne_by_the_ban"
    grants_new = "grants_trusted_funds_borrowings_risk_borne_bank"
    if grants_old not in existing_columns:
        if grants_new in existing_columns:
            op.alter_column(
                "fs_balance_sheet_type_four",
                grants_new,
                new_column_name=grants_old,
                existing_type=sa.INTEGER(),
                existing_nullable=False,
                existing_comment="V. Vốn tài trợ, uỷ thác đầu tư mà ngân hàng chịu rủi ro",
                comment="V. Vốn tài trợ, uỷ thác đầu tư mà ngân hàng chịu rủi ro",
            )
        else:
            op.add_column(
                "fs_balance_sheet_type_four",
                sa.Column(
                    grants_old,
                    sa.INTEGER(),
                    autoincrement=False,
                    nullable=False,
                    comment="V. Vốn tài trợ, uỷ thác đầu tư mà ngân hàng chịu rủi ro",
                ),
            )
    op.alter_column('fs_balance_sheet_type_four', 'total_liabilities_and_equity',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='TỔNG CỘNG NGUỒN VỐN',
               existing_nullable=False)
    op.alter_column('fs_balance_sheet_type_four', 'total_assets',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='TỔNG CỘNG TÀI SẢN',
               existing_nullable=False)
    op.alter_column('fs_balance_sheet_type_four', 'loans_to_customers_gross',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='1. Cho vay khách hàng',
               existing_nullable=False)
    op.alter_column('fs_balance_sheet_type_four', 'total_loans_to_customers',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='VII. Cho vay khách hàng',
               existing_nullable=False)
    op.alter_column('fs_balance_sheet_type_four', 'placements_with_other_credit_institutions',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='1. Tiền, Vàng gửi tại các TCTD khác',
               existing_nullable=False)
    op.alter_column('fs_balance_sheet_type_four', 'total_placements_with_and_loans_to_other_cis',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='IV. Tiền, vàng gửi tại các TCTD khác và cho vay các TCTD khác',
               existing_nullable=False)
    # ### end Alembic commands ###
