"""create newspapper table

Revision ID: 24b9a77e0bff
Revises: 0674ec513233
Create Date: 2026-05-27 19:57:09.489147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24b9a77e0bff'
down_revision: Union[str, Sequence[str], None] = '0674ec513233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fs_balance_sheet_type_one',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stock_id', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.String(), nullable=False),
    sa.Column('current_assets', sa.Integer(), nullable=False, comment='A. Tài sản lưu động và đầu tư ngắn hạn'),
    sa.Column('cash_and_cash_equivalents', sa.Integer(), nullable=False, comment='I. Tiền và các khoản tương đương tiền'),
    sa.Column('cash', sa.Integer(), nullable=False, comment='1. Tiền'),
    sa.Column('cash_equivalents', sa.Integer(), nullable=False, comment='2. Các khoản tương đương tiền'),
    sa.Column('short_term_financial_investments', sa.Integer(), nullable=False, comment='II. Các khoản đầu tư tài chính ngắn hạn'),
    sa.Column('trading_securities', sa.Integer(), nullable=False, comment='1. Chứng khoán kinh doanh'),
    sa.Column('provision_for_diminution_in_value_of_trading_securities', sa.Integer(), nullable=False, comment='2. Dự phòng giảm giá chứng khoán kinh doanh'),
    sa.Column('held_to_maturity_investments_short_term', sa.Integer(), nullable=False, comment='3. Đầu tư nắm giữ đến ngày đáo hạn'),
    sa.Column('short_term_receivables', sa.Integer(), nullable=False, comment='III. Các khoản phải thu ngắn hạn'),
    sa.Column('short_term_trade_receivables', sa.Integer(), nullable=False, comment='1. Phải thu ngắn hạn của khách hàng'),
    sa.Column('short_term_advances_to_suppliers', sa.Integer(), nullable=False, comment='2. Trả trước cho người bán'),
    sa.Column('short_term_internal_receivables', sa.Integer(), nullable=False, comment='3. Phải thu nội bộ ngắn hạn'),
    sa.Column('receivables_construction_contract_progress', sa.Integer(), nullable=False, comment='4. Phải thu theo tiến độ hợp đồng xây dựng'),
    sa.Column('short_term_loan_receivables', sa.Integer(), nullable=False, comment='5. Phải thu về cho vay ngắn hạn'),
    sa.Column('other_short_term_receivables', sa.Integer(), nullable=False, comment='6. Phải thu ngắn hạn khác'),
    sa.Column('provision_for_short_term_doubtful_debts', sa.Integer(), nullable=False, comment='7. Dự phòng phải thu ngắn hạn khó đòi'),
    sa.Column('inventories', sa.Integer(), nullable=False, comment='IV. Tổng hàng tồn kho'),
    sa.Column('gross_inventories', sa.Integer(), nullable=False, comment='1. Hàng tồn kho'),
    sa.Column('provision_for_decline_in_value_of_inventories', sa.Integer(), nullable=False, comment='2. Dự phòng giảm giá hàng tồn kho'),
    sa.Column('other_current_assets', sa.Integer(), nullable=False, comment='V. Tài sản ngắn hạn khác'),
    sa.Column('short_term_prepaid_expenses', sa.Integer(), nullable=False, comment='1. Chi phí trả trước ngắn hạn'),
    sa.Column('deductible_value_added_tax', sa.Integer(), nullable=False, comment='2. Thuế giá trị gia tăng được khấu trừ'),
    sa.Column('taxes_and_other_receivables_from_state_budget', sa.Integer(), nullable=False, comment='3. Thuế và các khoản phải thu Nhà nước'),
    sa.Column('government_bond_repo_transactions_short_term', sa.Integer(), nullable=False, comment='4. Giao dịch mua bán lại trái phiếu chính phủ'),
    sa.Column('other_current_assets_items', sa.Integer(), nullable=False, comment='5. Tài sản ngắn hạn khác'),
    sa.Column('non_current_assets', sa.Integer(), nullable=False, comment='B. Tài sản cố định và đầu tư dài hạn'),
    sa.Column('long_term_receivables', sa.Integer(), nullable=False, comment='I. Các khoản phải thu dài hạn'),
    sa.Column('long_term_trade_receivables', sa.Integer(), nullable=False, comment='1. Phải thu dài hạn của khách hàng'),
    sa.Column('working_capital_provided_to_subordinates', sa.Integer(), nullable=False, comment='2. Vốn kinh doanh tại các đơn vị trực thuộc'),
    sa.Column('long_term_internal_receivables', sa.Integer(), nullable=False, comment='3. Phải thu dài hạn nội bộ'),
    sa.Column('long_term_loan_receivables', sa.Integer(), nullable=False, comment='4. Phải thu về cho vay dài hạn'),
    sa.Column('other_long_term_receivables', sa.Integer(), nullable=False, comment='5. Phải thu dài hạn khác'),
    sa.Column('provision_for_long_term_doubtful_debts', sa.Integer(), nullable=False, comment='6. Dự phòng phải thu dài hạn khó đòi'),
    sa.Column('fixed_assets', sa.Integer(), nullable=False, comment='II. Tài sản cố định'),
    sa.Column('tangible_fixed_assets', sa.Integer(), nullable=False, comment='1. Tài sản cố định hữu hình'),
    sa.Column('tangible_fixed_assets_cost', sa.Integer(), nullable=False, comment='Nguyên giá'),
    sa.Column('tangible_fixed_assets_accumulated_depreciation', sa.Integer(), nullable=False, comment='Giá trị hao mòn lũy kế'),
    sa.Column('finance_lease_fixed_assets', sa.Integer(), nullable=False, comment='2. Tài sản cố định thuê tài chính'),
    sa.Column('finance_lease_fixed_assets_cost', sa.Integer(), nullable=False, comment='Nguyên giá (2)'),
    sa.Column('finance_lease_fixed_assets_accumulated_depreciation', sa.Integer(), nullable=False, comment='Giá trị hao mòn lũy kế (2)'),
    sa.Column('intangible_fixed_assets', sa.Integer(), nullable=False, comment='3. Tài sản cố định vô hình'),
    sa.Column('intangible_fixed_assets_cost', sa.Integer(), nullable=False, comment='Nguyên giá (3)'),
    sa.Column('intangible_fixed_assets_accumulated_amortization', sa.Integer(), nullable=False, comment='Giá trị hao mòn lũy kế (3)'),
    sa.Column('investment_properties', sa.Integer(), nullable=False, comment='III. Bất động sản đầu tư'),
    sa.Column('investment_properties_cost', sa.Integer(), nullable=False, comment='Nguyên giá (4)'),
    sa.Column('investment_properties_accumulated_depreciation', sa.Integer(), nullable=False, comment='Giá trị hao mòn lũy kế (4)'),
    sa.Column('long_term_assets_in_progress', sa.Integer(), nullable=False, comment='IV. Tài sản dở dang dài hạn'),
    sa.Column('long_term_work_in_progress', sa.Integer(), nullable=False, comment='1. Chi phí sản xuất, kinh doanh dở dang dài hạn'),
    sa.Column('construction_in_progress', sa.Integer(), nullable=False, comment='2. chi phí xây dựng cơ bản dở dang'),
    sa.Column('long_term_financial_investments', sa.Integer(), nullable=False, comment='V. Các khoản đầu tư tài chính dài hạn'),
    sa.Column('investments_in_subsidiaries', sa.Integer(), nullable=False, comment='1. Đầu tư vào công ty con'),
    sa.Column('investments_in_associates_and_joint_ventures', sa.Integer(), nullable=False, comment='2. Đầu tư vào công ty liên kết, liên doanh'),
    sa.Column('equity_investments_in_other_entities', sa.Integer(), nullable=False, comment='3. Đầu tư khác vào công cụ vốn'),
    sa.Column('provision_for_long_term_financial_investments', sa.Integer(), nullable=False, comment='4. Dự phòng giảm giá đầu tư tài chính dài hạn'),
    sa.Column('held_to_maturity_investments_long_term', sa.Integer(), nullable=False, comment='5. Đầu tư nắm giữ đến ngày đáo hạn'),
    sa.Column('other_non_current_assets', sa.Integer(), nullable=False, comment='VI. Tổng tài sản dài hạn khác'),
    sa.Column('long_term_prepaid_expenses', sa.Integer(), nullable=False, comment='1. Chi phí trả trước dài hạn'),
    sa.Column('deferred_corporate_income_tax_assets', sa.Integer(), nullable=False, comment='2. Tài sản Thuế thu nhập hoãn lại'),
    sa.Column('other_long_term_asset_items', sa.Integer(), nullable=False, comment='3. Tài sản dài hạn khác'),
    sa.Column('goodwill', sa.Integer(), nullable=False, comment='VII. Lợi thế thương mại'),
    sa.Column('total_assets', sa.Integer(), nullable=False, comment='TỔNG CỘNG TÀI SẢN'),
    sa.Column('total_liabilities', sa.Integer(), nullable=False, comment='A. Nợ phải trả'),
    sa.Column('current_liabilities', sa.Integer(), nullable=False, comment='I. Nợ ngắn hạn'),
    sa.Column('short_term_borrowings_and_finance_lease_liabilities', sa.Integer(), nullable=False, comment='1. Vay và nợ thuê tài chính ngắn hạn'),
    sa.Column('current_portion_of_long_term_borrowings_and_liabilities', sa.Integer(), nullable=False, comment='2. Vay và nợ dài hạn đến hạn phải trả'),
    sa.Column('short_term_trade_payables', sa.Integer(), nullable=False, comment='3. Phải trả người bán ngắn hạn'),
    sa.Column('short_term_advances_from_customers', sa.Integer(), nullable=False, comment='4. Người mua trả tiền trước'),
    sa.Column('statutory_obligations_and_taxes_payable', sa.Integer(), nullable=False, comment='5. Thuế và các khoản phải nộp nhà nước'),
    sa.Column('payables_to_employees', sa.Integer(), nullable=False, comment='6. Phải trả người lao động'),
    sa.Column('short_term_accrued_expenses', sa.Integer(), nullable=False, comment='7. Chi phí phải trả ngắn hạn'),
    sa.Column('short_term_internal_payables', sa.Integer(), nullable=False, comment='8. Phải trả nội bộ ngắn hạn'),
    sa.Column('payables_construction_contract_progress', sa.Integer(), nullable=False, comment='9. Phải trả theo tiến độ kế hoạch hợp đồng xây dựng'),
    sa.Column('short_term_unearned_revenue', sa.Integer(), nullable=False, comment='10. Doanh thu chưa thực hiện ngắn hạn'),
    sa.Column('other_short_term_payables', sa.Integer(), nullable=False, comment='11. Phải trả ngắn hạn khác'),
    sa.Column('short_term_provisions', sa.Integer(), nullable=False, comment='12. Dự phòng phải trả ngắn hạn'),
    sa.Column('bonus_and_welfare_fund', sa.Integer(), nullable=False, comment='13. Quỹ khen thưởng phúc lợi'),
    sa.Column('price_stabilization_fund', sa.Integer(), nullable=False, comment='14. Quỹ bình ổn giá'),
    sa.Column('government_bond_repo_transactions_liabilities', sa.Integer(), nullable=False, comment='15. Giao dịch mua bán lại trái phiếu chính phủ'),
    sa.Column('non_current_liabilities', sa.Integer(), nullable=False, comment='II. Nợ dài hạn'),
    sa.Column('long_term_trade_payables', sa.Integer(), nullable=False, comment='1. Phải trả người bán dài hạn'),
    sa.Column('long_term_accrued_expenses', sa.Integer(), nullable=False, comment='2. Chi phí phải trả dài hạn'),
    sa.Column('internal_payables_on_working_capital', sa.Integer(), nullable=False, comment='3. Phải trả nội bộ về vốn kinh doanh'),
    sa.Column('long_term_internal_payables', sa.Integer(), nullable=False, comment='4. Phải trả nội bộ dài hạn'),
    sa.Column('other_long_term_payables', sa.Integer(), nullable=False, comment='5. Phải trả dài hạn khác'),
    sa.Column('long_term_borrowings_and_finance_lease_liabilities', sa.Integer(), nullable=False, comment='6. Vay và nợ thuê tài chính dài hạn'),
    sa.Column('convertible_bonds', sa.Integer(), nullable=False, comment='7. Trái phiếu chuyển đổi'),
    sa.Column('deferred_corporate_income_tax_liabilities', sa.Integer(), nullable=False, comment='8. Thuế thu nhập hoãn lại phải trả'),
    sa.Column('provision_for_severance_allowances', sa.Integer(), nullable=False, comment='9. Dự phòng trợ cấp mất việc làm'),
    sa.Column('long_term_provisions', sa.Integer(), nullable=False, comment='10. Dự phòng phải trả dài hạn'),
    sa.Column('long_term_unearned_revenue', sa.Integer(), nullable=False, comment='11. Doanh thu chưa thực hiện dài hạn'),
    sa.Column('science_and_technology_development_fund', sa.Integer(), nullable=False, comment='12. Quỹ phát triển khoa học và công nghệ'),
    sa.Column('total_equity', sa.Integer(), nullable=False, comment='B. Nguồn vốn chủ sở hữu'),
    sa.Column('owners_equity', sa.Integer(), nullable=False, comment='I. Vốn chủ sở hữu'),
    sa.Column('contributed_charter_capital', sa.Integer(), nullable=False, comment='1. Vốn đầu tư của chủ sở hữu'),
    sa.Column('share_premium', sa.Integer(), nullable=False, comment='2. Thặng dư vốn cổ phần'),
    sa.Column('convertible_bond_options', sa.Integer(), nullable=False, comment='3. Quyền chọn chuyển đổi trái phiếu'),
    sa.Column('other_owners_equity', sa.Integer(), nullable=False, comment='4. Vốn khác của chủ sở hữu'),
    sa.Column('treasury_shares', sa.Integer(), nullable=False, comment='5. Cổ phiếu quỹ'),
    sa.Column('asset_revaluation_differences', sa.Integer(), nullable=False, comment='6. Chênh lệch đánh giá lại tài sản'),
    sa.Column('foreign_exchange_differences', sa.Integer(), nullable=False, comment='7. Chênh lệch tỷ giá hối đoái'),
    sa.Column('investment_and_development_fund', sa.Integer(), nullable=False, comment='8. Quỹ đầu tư phát triển'),
    sa.Column('financial_reserve_fund', sa.Integer(), nullable=False, comment='9. Quỹ dự phòng tài chính'),
    sa.Column('other_funds_belonging_to_equity', sa.Integer(), nullable=False, comment='10. Quỹ khác thuộc vốn chủ sở hữu'),
    sa.Column('undistributed_earnings_after_tax', sa.Integer(), nullable=False, comment='11. Lợi nhuận sau thuế chưa phân phối'),
    sa.Column('accumulated_retained_earnings_up_to_previous_period', sa.Integer(), nullable=False, comment='LNST chưa phân phối lũy kế đến cuối kỳ trước'),
    sa.Column('retained_earnings_for_current_period', sa.Integer(), nullable=False, comment='LNST chưa phân phối kỳ này'),
    sa.Column('capital_expenditure_fund', sa.Integer(), nullable=False, comment='12. Nguồn vốn đầu tư xây dựng cơ bản'),
    sa.Column('enterprise_rearrangement_support_fund', sa.Integer(), nullable=False, comment='13. Quỹ hỗ trợ sắp xếp doanh nghiệp'),
    sa.Column('non_controlling_interests', sa.Integer(), nullable=False, comment='14. Lợi ích của cổ đông không kiểm soát'),
    sa.Column('other_resources_and_funds', sa.Integer(), nullable=False, comment='II. Nguồn kinh phí và quỹ khác'),
    sa.Column('non_business_expenditure_source', sa.Integer(), nullable=False, comment='1. Nguồn kinh phí'),
    sa.Column('expenditure_source_formed_fixed_assets', sa.Integer(), nullable=False, comment='2. Nguồn kinh phí đã hình thành tài sản cố định'),
    sa.Column('job_loss_allowance_reserve_fund', sa.Integer(), nullable=False, comment='3. Quỹ dự phòng trợ cấp mất việc làm'),
    sa.Column('total_liabilities_and_equity', sa.Integer(), nullable=False, comment='TỔNG CỘNG NGUỒN VỐN'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fs_balance_sheet_type_one_quarter'), 'fs_balance_sheet_type_one', ['quarter'], unique=False)
    op.create_index(op.f('ix_fs_balance_sheet_type_one_stock_id'), 'fs_balance_sheet_type_one', ['stock_id'], unique=False)
    op.create_index(op.f('ix_fs_balance_sheet_type_one_year'), 'fs_balance_sheet_type_one', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fs_balance_sheet_type_one_year'), table_name='fs_balance_sheet_type_one')
    op.drop_index(op.f('ix_fs_balance_sheet_type_one_stock_id'), table_name='fs_balance_sheet_type_one')
    op.drop_index(op.f('ix_fs_balance_sheet_type_one_quarter'), table_name='fs_balance_sheet_type_one')
    op.drop_table('fs_balance_sheet_type_one')
    # ### end Alembic commands ###
