"""init tables

Revision ID: 2886f0ebbb5d
Revises: f4fe9dd7586d
Create Date: 2026-03-05 17:36:05.876093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2886f0ebbb5d'
down_revision: Union[str, Sequence[str], None] = 'f4fe9dd7586d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fund_nav',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fund_id', sa.String(length=255), nullable=False),
    sa.Column('stock_id', sa.String(length=255), nullable=False),
    sa.Column('business_sector', sa.String(length=255), nullable=False),
    sa.Column('gav', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fund_nav_business_sector'), 'fund_nav', ['business_sector'], unique=False)
    op.create_index(op.f('ix_fund_nav_fund_id'), 'fund_nav', ['fund_id'], unique=False)
    op.create_index(op.f('ix_fund_nav_stock_id'), 'fund_nav', ['stock_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fund_nav_stock_id'), table_name='fund_nav')
    op.drop_index(op.f('ix_fund_nav_fund_id'), table_name='fund_nav')
    op.drop_index(op.f('ix_fund_nav_business_sector'), table_name='fund_nav')
    op.drop_table('fund_nav')
    # ### end Alembic commands ###
