"""init tables

Revision ID: 39046d33f6a3
Revises: 4d4209120cdc
Create Date: 2026-03-12 12:08:01.752124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39046d33f6a3'
down_revision: Union[str, Sequence[str], None] = '4d4209120cdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foreign_trade',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stock_id', sa.String(length=255), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('foreign_room', sa.BigInteger(), nullable=True),
    sa.Column('buy_volume', sa.BigInteger(), nullable=True),
    sa.Column('sell_volume', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreign_trade_foreign_room'), 'foreign_trade', ['foreign_room'], unique=False)
    op.create_index(op.f('ix_foreign_trade_stock_id'), 'foreign_trade', ['stock_id'], unique=False)
    op.create_index(op.f('ix_foreign_trade_trading_date'), 'foreign_trade', ['trading_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_foreign_trade_trading_date'), table_name='foreign_trade')
    op.drop_index(op.f('ix_foreign_trade_stock_id'), table_name='foreign_trade')
    op.drop_index(op.f('ix_foreign_trade_foreign_room'), table_name='foreign_trade')
    op.drop_table('foreign_trade')
    # ### end Alembic commands ###
