"""recreate vn index table

Revision ID: 3b5023d395c8
Revises: 34b2f5b41292
Create Date: 2026-04-12 06:08:33.254437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b5023d395c8'
down_revision: Union[str, Sequence[str], None] = '34b2f5b41292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_index',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('open_index_value', sa.Integer(), nullable=False),
    sa.Column('highest_index_value', sa.Integer(), nullable=False),
    sa.Column('lowest_index_value', sa.Integer(), nullable=False),
    sa.Column('close_index_value', sa.Integer(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('index_type', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_index_index_type'), 'stock_index', ['index_type'], unique=False)
    op.create_index(op.f('ix_stock_index_trading_date'), 'stock_index', ['trading_date'], unique=False)
    op.drop_index(op.f('ix_vn_index_index_type'), table_name='vn_index')
    op.drop_index(op.f('ix_vn_index_trading_date'), table_name='vn_index')
    op.drop_table('vn_index')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vn_index',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('trading_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('open_index_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('highest_index_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lowest_index_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('close_index_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('volume', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('index_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('vn_index_pkey'))
    )
    op.create_index(op.f('ix_vn_index_trading_date'), 'vn_index', ['trading_date'], unique=False)
    op.create_index(op.f('ix_vn_index_index_type'), 'vn_index', ['index_type'], unique=False)
    op.drop_index(op.f('ix_stock_index_trading_date'), table_name='stock_index')
    op.drop_index(op.f('ix_stock_index_index_type'), table_name='stock_index')
    op.drop_table('stock_index')
    # ### end Alembic commands ###
