"""create newspapper table

Revision ID: 3f9ad2c26465
Revises: 00dc794db8f2
Create Date: 2026-05-28 15:22:55.427516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f9ad2c26465'
down_revision: Union[str, Sequence[str], None] = '00dc794db8f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fs_financial_statistics_overview_type_one',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stock_id', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.String(length=10), nullable=False),
    sa.Column('p_e', sa.Float(), nullable=False, comment='P/E'),
    sa.Column('p_s', sa.Float(), nullable=False, comment='P/S'),
    sa.Column('p_b', sa.Float(), nullable=False, comment='P/B'),
    sa.Column('eps', sa.Float(), nullable=False, comment='EPS'),
    sa.Column('net_profit_margin', sa.Float(), nullable=False, comment='Tỷ lệ lãi ròng (%)'),
    sa.Column('gross_profit_margin', sa.Float(), nullable=False, comment='Tỷ lệ lãi gộp (%)'),
    sa.Column('ebit_margin', sa.Float(), nullable=False, comment='Tỷ lệ EBIT (%)'),
    sa.Column('operating_profit_margin', sa.Float(), nullable=False, comment='Tỷ lệ lãi từ HĐKD (%)'),
    sa.Column('current_ratio', sa.Float(), nullable=False, comment='Thanh toán hiện hành'),
    sa.Column('quick_ratio', sa.Float(), nullable=False, comment='Thanh toán nhanh'),
    sa.Column('interest_coverage_ratio', sa.Float(), nullable=False, comment='Thanh toán lãi vay'),
    sa.Column('debt_to_equity', sa.Float(), nullable=False, comment='Nợ/VCSH'),
    sa.Column('roa', sa.Float(), nullable=False, comment='ROA (%)'),
    sa.Column('roe', sa.Float(), nullable=False, comment='ROE (%)'),
    sa.Column('roic', sa.Float(), nullable=False, comment='ROIC (%)'),
    sa.Column('roce', sa.Float(), nullable=False, comment='ROCE (%)'),
    sa.Column('total_asset_turnover', sa.Float(), nullable=False, comment='Vòng quay tổng TS'),
    sa.Column('inventory_turnover', sa.Float(), nullable=False, comment='Vòng quay HTK'),
    sa.Column('receivables_turnover', sa.Float(), nullable=False, comment='Vòng quay các KPT'),
    sa.Column('short_term_asset_turnover', sa.Float(), nullable=False, comment='Vòng quay TSNH'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fs_financial_statistics_overview_type_one_quarter'), 'fs_financial_statistics_overview_type_one', ['quarter'], unique=False)
    op.create_index(op.f('ix_fs_financial_statistics_overview_type_one_stock_id'), 'fs_financial_statistics_overview_type_one', ['stock_id'], unique=False)
    op.create_index(op.f('ix_fs_financial_statistics_overview_type_one_year'), 'fs_financial_statistics_overview_type_one', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fs_financial_statistics_overview_type_one_year'), table_name='fs_financial_statistics_overview_type_one')
    op.drop_index(op.f('ix_fs_financial_statistics_overview_type_one_stock_id'), table_name='fs_financial_statistics_overview_type_one')
    op.drop_index(op.f('ix_fs_financial_statistics_overview_type_one_quarter'), table_name='fs_financial_statistics_overview_type_one')
    op.drop_table('fs_financial_statistics_overview_type_one')
    # ### end Alembic commands ###
