"""delete vn index table

Revision ID: 41d4c1d3375e
Revises: 5adecdda182e
Create Date: 2026-04-12 06:04:31.909929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41d4c1d3375e'
down_revision: Union[str, Sequence[str], None] = '5adecdda182e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vn_index_trading_date'), table_name='vn_index')
    op.drop_table('vn_index')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vn_index',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('trading_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('open_index_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('highest_index_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lowest_index_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('close_index_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('volume', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('vn_index_pkey'))
    )
    op.create_index(op.f('ix_vn_index_trading_date'), 'vn_index', ['trading_date'], unique=False)
    # ### end Alembic commands ###
