"""create newspapper table

Revision ID: 58315e48d475
Revises: 24b9a77e0bff
Create Date: 2026-05-27 20:24:04.926205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58315e48d475'
down_revision: Union[str, Sequence[str], None] = '24b9a77e0bff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income_statement_type_four',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stock_id', sa.String(), nullable=False, comment='Mã cổ phiếu'),
    sa.Column('year', sa.Integer(), nullable=False, comment='Năm tài chính'),
    sa.Column('quarter', sa.String(), nullable=False, comment='Quý'),
    sa.Column('cash_gold_and_valuables', sa.Integer(), nullable=False, comment='I. Tiền mặt, chứng từ có giá trị, ngoại tệ, kim loại quý, đá quý'),
    sa.Column('balances_with_the_sbv', sa.Integer(), nullable=False, comment='II. Tiền gửi tại NHNN'),
    sa.Column('treasury_bills_and_eligible_short_term_valuable_papers', sa.Integer(), nullable=False, comment='III. Tín phiếu kho bạc và các giấy tờ có giá ngắn hạn đủ tiêu chuẩn khác'),
    sa.Column('total_placements_with_and_loans_to_other_cis', sa.Integer(), nullable=False, comment='IV. Tiền, vàng gửi tại các TCTD khác và cho vay các TCTD khác'),
    sa.Column('placements_with_other_credit_institutions', sa.Integer(), nullable=False, comment='1. Tiền, Vàng gửi tại các TCTD khác'),
    sa.Column('loans_to_other_credit_institutions', sa.Integer(), nullable=False, comment='2. Cho vay các TCTD khác'),
    sa.Column('allowance_for_loans_to_other_credit_institutions', sa.Integer(), nullable=False, comment='3. Dự phòng rủi ro cho vay các TCTD khác'),
    sa.Column('total_trading_securities', sa.Integer(), nullable=False, comment='V. Chứng khoán kinh doanh'),
    sa.Column('trading_securities_gross', sa.Integer(), nullable=False, comment='1. Chứng khoán kinh doanh'),
    sa.Column('allowance_for_diminution_in_value_of_trading_securities', sa.Integer(), nullable=False, comment='2. Dự phòng giảm giá chứng khoán kinh doanh'),
    sa.Column('derivative_financial_instruments_and_other_assets', sa.Integer(), nullable=False, comment='VI. Các công cụ tài chính phái sinh và các tài sản tài chính khác'),
    sa.Column('total_loans_to_customers', sa.Integer(), nullable=False, comment='VII. Cho vay khách hàng'),
    sa.Column('loans_to_customers_gross', sa.Integer(), nullable=False, comment='1. Cho vay khách hàng'),
    sa.Column('allowance_for_loans_to_customers', sa.Integer(), nullable=False, comment='2. Dự phòng rủi ro cho vay khách hàng'),
    sa.Column('total_investment_securities', sa.Integer(), nullable=False, comment='VIII. Chứng khoán đầu tư'),
    sa.Column('available_for_sale_investment_securities', sa.Integer(), nullable=False, comment='1. Chứng khoán đầu tư sẵn sàng để bán'),
    sa.Column('held_to_maturity_investment_securities', sa.Integer(), nullable=False, comment='2. Chứng khoán đầu tư giữ đến ngày đáo hạn'),
    sa.Column('allowance_for_diminution_in_value_of_investment_securities', sa.Integer(), nullable=False, comment='3. Dự phòng giảm giá chứng khoán đầu tư'),
    sa.Column('total_long_term_investments', sa.Integer(), nullable=False, comment='IX. Góp vốn đầu tư dài hạn'),
    sa.Column('investments_in_subsidiaries', sa.Integer(), nullable=False, comment='1. Đầu tư vào công ty con'),
    sa.Column('investments_in_joint_ventures', sa.Integer(), nullable=False, comment='2. Góp vốn liên doanh'),
    sa.Column('investments_in_associates', sa.Integer(), nullable=False, comment='3. Đầu tư vào công ty liên kết'),
    sa.Column('other_long_term_investments', sa.Integer(), nullable=False, comment='4. Đầu tư dài hạn khác'),
    sa.Column('allowance_for_diminution_in_value_of_long_term_investments', sa.Integer(), nullable=False, comment='5. Dự phòng giảm giá đầu tư dài hạn'),
    sa.Column('total_fixed_assets', sa.Integer(), nullable=False, comment='X. Tài sản cố định'),
    sa.Column('tangible_fixed_assets', sa.Integer(), nullable=False, comment='1. Tài sản cố định hữu hình'),
    sa.Column('tangible_fixed_assets_cost', sa.Integer(), nullable=False, comment='Nguyên giá'),
    sa.Column('tangible_fixed_assets_accumulated_depreciation', sa.Integer(), nullable=False, comment='Giá trị hao mòn lũy kế'),
    sa.Column('finance_lease_fixed_assets', sa.Integer(), nullable=False, comment='2. Tài sản cố định thuê tài chính'),
    sa.Column('finance_lease_fixed_assets_cost', sa.Integer(), nullable=False, comment='Nguyên giá (2)'),
    sa.Column('finance_lease_fixed_assets_accumulated_depreciation', sa.Integer(), nullable=False, comment='Giá trị hao mòn lũy kế (2)'),
    sa.Column('intangible_fixed_assets', sa.Integer(), nullable=False, comment='3. Tài sản cố định vô hình'),
    sa.Column('intangible_fixed_assets_cost', sa.Integer(), nullable=False, comment='Nguyên giá (3)'),
    sa.Column('intangible_fixed_assets_accumulated_amortization', sa.Integer(), nullable=False, comment='Giá trị hao mòn lũy kế (3)'),
    sa.Column('construction_in_progress', sa.Integer(), nullable=False, comment='5. Chi phí XDCB dở dang'),
    sa.Column('investment_properties', sa.Integer(), nullable=False, comment='XI. Bất động sản đầu tư'),
    sa.Column('investment_properties_cost', sa.Integer(), nullable=False, comment='Nguyên giá (4)'),
    sa.Column('investment_properties_accumulated_depreciation', sa.Integer(), nullable=False, comment='Giá trị hao mòn lũy kế (4)'),
    sa.Column('total_other_assets', sa.Integer(), nullable=False, comment='XII. Tài sản có khác'),
    sa.Column('other_receivables', sa.Integer(), nullable=False, comment='1. Các khoản phải thu'),
    sa.Column('accrued_interest_and_fees_receivable', sa.Integer(), nullable=False, comment='2. Các khoản lãi, phí phải thu'),
    sa.Column('deferred_corporate_income_tax_assets', sa.Integer(), nullable=False, comment='3. Tài sản thuế TNDN hoãn lại'),
    sa.Column('other_asset_items', sa.Integer(), nullable=False, comment='4. Tài sản có khác'),
    sa.Column('goodwill', sa.Integer(), nullable=False, comment='Trong đó: Lợi thế thương mại'),
    sa.Column('allowance_for_other_on_balance_sheet_assets', sa.Integer(), nullable=False, comment='5. Các khoản dự phòng rủi ro cho các tài sản có nội bảng khác'),
    sa.Column('total_assets', sa.Integer(), nullable=False, comment='TỔNG CỘNG TÀI SẢN'),
    sa.Column('borrowings_from_the_government_and_the_sbv', sa.Integer(), nullable=False, comment='I. Các khoản nợ chính phủ và NHNN'),
    sa.Column('total_deposits_and_borrowings_from_other_cis', sa.Integer(), nullable=False, comment='II. Tiền gửi và cho vay các TCTD khác'),
    sa.Column('deposits_from_other_credit_institutions', sa.Integer(), nullable=False, comment='1. Tiền gửi các tổ chức tín dụng khác'),
    sa.Column('borrowings_from_other_credit_institutions', sa.Integer(), nullable=False, comment='2. Vay các TCTD khác'),
    sa.Column('deposits_from_customers', sa.Integer(), nullable=False, comment='III. Tiền gửi khách hàng'),
    sa.Column('derivative_financial_instruments_and_other_financial_liabilities', sa.Integer(), nullable=False, comment='IV. Các công cụ tài chính phái sinh và các khoản nợ tài chính khác'),
    sa.Column('grants_trusted_funds_and_borrowings_with_risks_borne_by_the_bank', sa.Integer(), nullable=False, comment='V. Vốn tài trợ, uỷ thác đầu tư mà ngân hàng chịu rủi ro'),
    sa.Column('valuable_papers_issued', sa.Integer(), nullable=False, comment='VI. Phát hành giấy tờ có giá'),
    sa.Column('total_other_liabilities', sa.Integer(), nullable=False, comment='VII. Các khoản nợ khác'),
    sa.Column('accrued_interest_and_fees_payable', sa.Integer(), nullable=False, comment='1. Các khoản lãi, phí phải trả'),
    sa.Column('deferred_corporate_income_tax_liabilities', sa.Integer(), nullable=False, comment='2.Thuế TNDN hoãn lại phải trả'),
    sa.Column('other_payables_and_liabilities', sa.Integer(), nullable=False, comment='3. Các khoản phải trả và công nợ khác'),
    sa.Column('other_provisions', sa.Integer(), nullable=False, comment='4. Dự phòng rủi ro khác'),
    sa.Column('total_capital_and_reserves', sa.Integer(), nullable=False, comment='VIII. Vốn và các quỹ'),
    sa.Column('credit_institution_capital', sa.Integer(), nullable=False, comment='1. Vốn của Tổ chức tín dụng'),
    sa.Column('charter_capital', sa.Integer(), nullable=False, comment='Vốn điều lệ'),
    sa.Column('capital_expenditure_fund', sa.Integer(), nullable=False, comment='Vốn đầu tư XDCB'),
    sa.Column('share_premium', sa.Integer(), nullable=False, comment='Thặng dư vốn cổ phần'),
    sa.Column('treasury_shares', sa.Integer(), nullable=False, comment='Cổ phiếu quỹ'),
    sa.Column('preferred_shares', sa.Integer(), nullable=False, comment='Cổ phiếu ưu đãi'),
    sa.Column('other_capital', sa.Integer(), nullable=False, comment='Vốn khác'),
    sa.Column('funds_of_the_credit_institution', sa.Integer(), nullable=False, comment='2. Quỹ của TCTD'),
    sa.Column('foreign_exchange_differences', sa.Integer(), nullable=False, comment='3. Chênh lệch tỷ giá hối đoái'),
    sa.Column('asset_revaluation_differences', sa.Integer(), nullable=False, comment='4. Chênh lệch đánh giá lại tài sản'),
    sa.Column('retained_earnings_or_accumulated_losses', sa.Integer(), nullable=False, comment='5. Lợi nhuận chưa phân phối/Lỗ lũy kế'),
    sa.Column('other_reserves_and_funds', sa.Integer(), nullable=False, comment='6. Nguồn kinh phí, Quỹ khác'),
    sa.Column('non_controlling_interests', sa.Integer(), nullable=False, comment='IX. Lợi ích của cổ đông thiểu số'),
    sa.Column('total_liabilities_and_equity', sa.Integer(), nullable=False, comment='TỔNG CỘNG NGUỒN VỐN'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('income_statement_type_four')
    # ### end Alembic commands ###
