"""create income statement type four

Revision ID: 67141760a03c
Revises: 3e6c539df06a
Create Date: 2026-05-27 09:55:04.906673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67141760a03c'
down_revision: Union[str, Sequence[str], None] = '3e6c539df06a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fs_income_statement_type_four',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stock_id', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.String(), nullable=False),
    sa.Column('net_interest_income', sa.Integer(), nullable=False, comment='Thu nhập lãi thuần'),
    sa.Column('interest_and_similar_income', sa.Integer(), nullable=False, comment='Thu nhập từ lãi và các khoản thu nhập tương tự'),
    sa.Column('interest_and_similar_expenses', sa.Integer(), nullable=False, comment='Chi phí lãi và các chi phí tương tự'),
    sa.Column('net_fee_and_commission_income', sa.Integer(), nullable=False, comment='Lãi/Lỗ thuần từ hoạt động dịch vụ'),
    sa.Column('fee_and_commission_income', sa.Integer(), nullable=False, comment='Thu nhập từ hoạt động dịch vụ'),
    sa.Column('fee_and_commission_expenses', sa.Integer(), nullable=False, comment='Chi phí hoạt động dịch vụ'),
    sa.Column('net_gain_loss_from_foreign_currency_and_gold_dealings', sa.Integer(), nullable=False, comment='Lãi/Lỗ thuần từ hoạt động kinh doanh ngoại hối'),
    sa.Column('net_gain_loss_from_trading_securities', sa.Integer(), nullable=False, comment='Lãi/Lỗ thuần từ mua bán chứng khoán kinh doanh'),
    sa.Column('net_gain_loss_from_investment_securities', sa.Integer(), nullable=False, comment='Lãi/Lỗ thuần từ mua bán chứng khoán đầu tư'),
    sa.Column('net_gain_loss_from_other_operating_activities', sa.Integer(), nullable=False, comment='Lãi/Lỗ thuần từ hoạt động khác'),
    sa.Column('other_operating_income', sa.Integer(), nullable=False, comment='Thu nhập từ hoạt động khác'),
    sa.Column('other_operating_expenses', sa.Integer(), nullable=False, comment='Chi phí hoạt động khác'),
    sa.Column('income_from_long_term_investments', sa.Integer(), nullable=False, comment='Thu nhập từ hoạt động góp vốn mua cổ phần'),
    sa.Column('operating_expenses', sa.Integer(), nullable=False, comment='Chi phí hoạt động'),
    sa.Column('net_operating_profit_before_provision_for_credit_losses', sa.Integer(), nullable=False, comment='Lợi nhuận từ HDKD trước chi phí dự phòng rủi ro tín dụng'),
    sa.Column('provision_expenses_for_credit_losses', sa.Integer(), nullable=False, comment='Chi phí dự phòng rủi ro tín dụng'),
    sa.Column('total_accounting_profit_before_tax', sa.Integer(), nullable=False, comment='Tổng lợi nhuận trước thuế'),
    sa.Column('corporate_income_tax_expense', sa.Integer(), nullable=False, comment='Chi phí thuế TNDN'),
    sa.Column('current_corporate_income_tax_expense', sa.Integer(), nullable=False, comment='Chi phí thuế thu nhập hiện hành'),
    sa.Column('deferred_corporate_income_tax_expense', sa.Integer(), nullable=False, comment='Chi phí thuế TNDN giữ lại'),
    sa.Column('net_profit_after_corporate_income_tax', sa.Integer(), nullable=False, comment='Lợi nhuận sau thuế thu nhập doanh nghiệp'),
    sa.Column('non_controlling_interests_and_preferred_dividends', sa.Integer(), nullable=False, comment='Lợi ích của cổ đông thiểu số và cổ tức ưu đãi'),
    sa.Column('net_profit_parent', sa.Integer(), nullable=False, comment='LNST sau khi điều chỉnh Lợi ích của CĐTS và Cổ tức ưu đãi'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fs_income_statement_type_four_quarter'), 'fs_income_statement_type_four', ['quarter'], unique=False)
    op.create_index(op.f('ix_fs_income_statement_type_four_stock_id'), 'fs_income_statement_type_four', ['stock_id'], unique=False)
    op.create_index(op.f('ix_fs_income_statement_type_four_year'), 'fs_income_statement_type_four', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fs_income_statement_type_four_year'), table_name='fs_income_statement_type_four')
    op.drop_index(op.f('ix_fs_income_statement_type_four_stock_id'), table_name='fs_income_statement_type_four')
    op.drop_index(op.f('ix_fs_income_statement_type_four_quarter'), table_name='fs_income_statement_type_four')
    op.drop_table('fs_income_statement_type_four')
    # ### end Alembic commands ###
