"""create stock price table

Revision ID: 67d5c95dc720
Revises: 3ffab288ce3c
Create Date: 2026-03-08 09:58:59.361116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67d5c95dc720'
down_revision: Union[str, Sequence[str], None] = '3ffab288ce3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_price',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stock_id', sa.String(length=255), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_price_stock_id'), 'stock_price', ['stock_id'], unique=False)
    op.create_index(op.f('ix_stock_price_trading_date'), 'stock_price', ['trading_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_price_trading_date'), table_name='stock_price')
    op.drop_index(op.f('ix_stock_price_stock_id'), table_name='stock_price')
    op.drop_table('stock_price')
    # ### end Alembic commands ###
