"""create vn-index table

Revision ID: 6c515143bcfa
Revises: 2f75e345e1ff
Create Date: 2026-03-26 20:10:14.261426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c515143bcfa'
down_revision: Union[str, Sequence[str], None] = '2f75e345e1ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vn_index_stock_id'), table_name='vn_index')
    op.drop_column('vn_index', 'stock_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vn_index', sa.Column('stock_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_vn_index_stock_id'), 'vn_index', ['stock_id'], unique=False)
    # ### end Alembic commands ###
