"""create newspapper table

Revision ID: 76e876fd0be8
Revises: 67141760a03c
Create Date: 2026-05-27 11:23:43.512368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76e876fd0be8'
down_revision: Union[str, Sequence[str], None] = '67141760a03c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fs_income_statement_type_three',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stock_id', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.String(), nullable=False),
    sa.Column('gain_from_fvtpl_financial_assets', sa.Integer(), nullable=False, comment='1.1. Lãi từ các tài sản tài chính ghi nhận thông qua lãi/lỗ (FVTPL)'),
    sa.Column('gain_on_disposal_of_financial_assets', sa.Integer(), nullable=False, comment='a. Lãi bán các tài sản tài chính'),
    sa.Column('positive_revaluation_difference_of_fvtpl_financial_assets', sa.Integer(), nullable=False, comment='b. Chênh lệch tăng đánh giá lại các TSTC thông qua lãi/lỗ'),
    sa.Column('dividends_and_interest_from_fvtpl_financial_assets', sa.Integer(), nullable=False, comment='c. Cổ tức, tiền lãi phát sinh từ tài sản tài chính PVTPL'),
    sa.Column('interest_from_htm_investments', sa.Integer(), nullable=False, comment='1.2. Lãi từ các khoản đầu tư nắm giữ đến ngày đáo hạn (HTM)'),
    sa.Column('interest_from_loans_and_receivables', sa.Integer(), nullable=False, comment='1.3. Lãi từ các khoản cho vay và phải thu'),
    sa.Column('gain_from_afs_financial_assets', sa.Integer(), nullable=False, comment='1.4. Lãi từ các tài sản tài chính sẵn sàng để bán (AFS)'),
    sa.Column('gain_from_hedging_derivatives', sa.Integer(), nullable=False, comment='1.5. Lãi từ các công cụ phái sinh phòng ngừa rủi ro'),
    sa.Column('brokerage_revenue', sa.Integer(), nullable=False, comment='1.6. Doanh thu môi giới chứng khoán'),
    sa.Column('underwriting_and_agency_revenue', sa.Integer(), nullable=False, comment='1.7. Doanh thu bảo lãnh, đại lý phát hành chứng khoán'),
    sa.Column('advisory_revenue', sa.Integer(), nullable=False, comment='1.8. Doanh thu tư vấn'),
    sa.Column('custody_and_auction_revenue', sa.Integer(), nullable=False, comment='1.9. Doanh thu hoạt động nhận ủy thác, đấu giá'),
    sa.Column('securities_depository_revenue', sa.Integer(), nullable=False, comment='1.10. Doanh thu lưu ký chứng khoán'),
    sa.Column('other_operating_income', sa.Integer(), nullable=False, comment='1.11. Thu nhập hoạt động khác'),
    sa.Column('total_operating_revenue', sa.Integer(), nullable=False, comment='Cộng doanh thu hoạt động'),
    sa.Column('operating_expenses', sa.Integer(), nullable=False, comment='II. CHI PHÍ HOẠT ĐỘNG'),
    sa.Column('loss_from_fvtpl_financial_assets', sa.Integer(), nullable=False, comment='2.1. Lỗ các tài sản tài chính ghi nhận thông qua lãi/lỗ (FVTPL)'),
    sa.Column('loss_on_disposal_of_financial_assets', sa.Integer(), nullable=False, comment='a. Lỗ bán các tài sản tài chính'),
    sa.Column('negative_revaluation_difference_of_fvtpl_financial_assets', sa.Integer(), nullable=False, comment='b. Chênh lệch giảm đánh giá lại các TSTC thông qua lãi/lỗ'),
    sa.Column('transaction_costs_of_purchasing_fvtpl_financial_assets', sa.Integer(), nullable=False, comment='c. c.Chi phí giao dịch mua các tài sản tài chính FVTPL'),
    sa.Column('loss_from_htm_investments', sa.Integer(), nullable=False, comment='2.2. Lỗ các khoản đầu tư nắm giữ đến ngày đáo hạn (HTM)'),
    sa.Column('interest_expenses_and_loss_from_loans_and_receivables', sa.Integer(), nullable=False, comment='2.3. Chi phí lãi vay, lỗ từ các khoản cho vay và phải thu'),
    sa.Column('loss_on_disposal_of_afs_financial_assets', sa.Integer(), nullable=False, comment='2.4. Lỗ bán các tài sản tài chính sẵn sàng để bán (AFS)'),
    sa.Column('loss_from_hedging_derivatives', sa.Integer(), nullable=False, comment='2.5. Lỗ từ các tài sản tài chính phái sinh phòng ngừa rủi ro'),
    sa.Column('proprietary_trading_expenses', sa.Integer(), nullable=False, comment='2.6. Chi phí hoạt động tự doanh'),
    sa.Column('brokerage_expenses', sa.Integer(), nullable=False, comment='2.7. Chi phí môi giới chứng khoán'),
    sa.Column('underwriting_and_agency_expenses', sa.Integer(), nullable=False, comment='2.8. Chi phí hoạt động bảo lãnh, đại lý phát hành chứng khoán'),
    sa.Column('advisory_expenses', sa.Integer(), nullable=False, comment='2.9. Chi phí tư vấn'),
    sa.Column('custody_and_auction_expenses', sa.Integer(), nullable=False, comment='2.10. Chi phí hoạt động đấu giá, ủy thác'),
    sa.Column('securities_depository_expenses', sa.Integer(), nullable=False, comment='2.11. Chi phí lưu ký chứng khoán'),
    sa.Column('other_expenses', sa.Integer(), nullable=False, comment='2.12. Chi phí khác'),
    sa.Column('of_which_error_correction_expenses', sa.Integer(), nullable=False, comment='Trong đó: Chi phí sửa lỗi giao dịch chứng khoán, lỗi khác'),
    sa.Column('total_operating_expenses', sa.Integer(), nullable=False, comment='Cộng chi phí hoạt động'),
    sa.Column('financial_income', sa.Integer(), nullable=False, comment='III. DOANH THU HOẠT ĐỘNG TÀI CHÍNH'),
    sa.Column('realized_and_unrealized_foreign_exchange_gains', sa.Integer(), nullable=False, comment='3.1. Chênh lệch lãi tỷ giá hối đoái đã và chưa thực hiện'),
    sa.Column('dividends_and_interest_income_from_deposits', sa.Integer(), nullable=False, comment='3.2. Doanh thu, dự thu cổ tức, lãi tiền gửi không cố định phát sinh trong kỳ'),
    sa.Column('gains_from_disposal_of_subsidiaries_and_associates', sa.Integer(), nullable=False, comment='3.3. Lãi bán, thanh lý các khoản đầu tư vào công ty con, liên kết, liên doanh'),
    sa.Column('other_investment_income', sa.Integer(), nullable=False, comment='3.4. Doanh thu khác về đầu tư'),
    sa.Column('total_financial_income', sa.Integer(), nullable=False, comment='Cộng doanh thu hoạt động tài chính'),
    sa.Column('financial_expenses', sa.Integer(), nullable=False, comment='IV. CHI PHÍ TÀI CHÍNH'),
    sa.Column('realized_and_unrealized_foreign_exchange_losses', sa.Integer(), nullable=False, comment='4.1. Chênh lệch lỗ tỷ giá hối đoái đã và chưa thực hiện'),
    sa.Column('interest_expense', sa.Integer(), nullable=False, comment='4.2. Chi phí lãi vay'),
    sa.Column('losses_from_disposal_of_subsidiaries_and_associates', sa.Integer(), nullable=False, comment='4.3. Lỗ bán, thanh lý các khoản đầu tư vào công ty con, liên kết, liên doanh'),
    sa.Column('other_investment_expenses', sa.Integer(), nullable=False, comment='4.4. Chi phí đầu tư khác'),
    sa.Column('total_financial_expenses', sa.Integer(), nullable=False, comment='Cộng chi phí tài chính'),
    sa.Column('selling_expenses', sa.Integer(), nullable=False, comment='V. CHI BÁN HÀNG'),
    sa.Column('general_and_administrative_expenses', sa.Integer(), nullable=False, comment='VI. CHI PHÍ QUẢN LÝ CÔNG TY CHỨNG KHOÁN'),
    sa.Column('net_operating_profit', sa.Integer(), nullable=False, comment='VII. KẾT QUẢ HOẠT ĐỘNG'),
    sa.Column('other_income_and_expenses', sa.Integer(), nullable=False, comment='VIII. THU NHẬP KHÁC VÀ CHI PHÍ KHÁC'),
    sa.Column('other_income', sa.Integer(), nullable=False, comment='8.1. Thu nhập khác'),
    sa.Column('other_expenses_non_operating', sa.Integer(), nullable=False, comment='8.2. Chi phí khác'),
    sa.Column('other_profit', sa.Integer(), nullable=False, comment='Cộng kết quả hoạt động khác'),
    sa.Column('total_accounting_profit_before_tax', sa.Integer(), nullable=False, comment='IX. TỔNG LỢI NHUẬN KẾ TOÁN TRƯỚC THUẾ'),
    sa.Column('realized_profit', sa.Integer(), nullable=False, comment='9.1. Lợi nhuận đã thực hiện'),
    sa.Column('unrealized_profit', sa.Integer(), nullable=False, comment='9.2. Lợi nhuận chưa thực hiện'),
    sa.Column('corporate_income_tax_expense', sa.Integer(), nullable=False, comment='X. CHI PHÍ THUẾ TNDN'),
    sa.Column('current_corporate_income_tax_expense', sa.Integer(), nullable=False, comment='10.1. Chi phí thuế TNDN hiện hành'),
    sa.Column('deferred_corporate_income_tax_expense', sa.Integer(), nullable=False, comment='10.2. Chi phí thuế TNDN hoãn lại'),
    sa.Column('net_profit_after_corporate_income_tax', sa.Integer(), nullable=False, comment='XI. LỢI NHUẬN KẾ TOÁN SAU THUẾ TNDN'),
    sa.Column('net_profit_parent', sa.Integer(), nullable=False, comment='11.1. Lợi nhuận sau thuế phân bổ cho chủ sở hữu'),
    sa.Column('net_profit_appropriated_to_reserves', sa.Integer(), nullable=False, comment='11.2. Lợi nhuận sau thuế trích các Quỹ dự trữ điều lệ, Quỹ Dự phòng tài chính và rủi ro nghề nghiệp theo quy định của Điều lệ Công ty là %)'),
    sa.Column('non_controlling_interests', sa.Integer(), nullable=False, comment='11.3. Lợi nhuận thuần phân bổ cho lợi ích của cổ đông không kiểm soát'),
    sa.Column('other_comprehensive_income_after_tax', sa.Integer(), nullable=False, comment='XII. THU NHẬP (LỖ) TOÀN DIỆN KHÁC SAU THUẾ TNDN'),
    sa.Column('gain_loss_from_revaluation_of_htm_investments', sa.Integer(), nullable=False, comment='12.1. Lãi/(Lỗ) từ đánh giá lại các các khoản đầu tư giữ đến ngày đáo hạn'),
    sa.Column('gain_loss_from_revaluation_of_afs_financial_assets', sa.Integer(), nullable=False, comment='12.2.Lãi/(Lỗ) từ đánh giá lại các tài sản tài chính sẵn sàng để bán'),
    sa.Column('share_of_other_comprehensive_income_of_subsidiaries_and_associates', sa.Integer(), nullable=False, comment='12.3. Lãi (lỗ) toàn diện khác được chia từ hoạt động đầu tư vào công ty con, công ty liên kết, liên doanh'),
    sa.Column('gain_loss_from_revaluation_of_derivative_financial_instruments', sa.Integer(), nullable=False, comment='12.4. Lãi/(Lỗ) từ đánh giá lại các công cụ tài chính phái sinh'),
    sa.Column('foreign_exchange_differences_from_foreign_operations', sa.Integer(), nullable=False, comment='12.5. Lãi/(lỗ) chênh lệch tỷ giá của hoạt động tại nước ngoài'),
    sa.Column('unallocated_gains_losses_from_subsidiaries_and_associates', sa.Integer(), nullable=False, comment='12.6. Lãi, lỗ từ các khoản đầu tư vào công ty con, công ty liên kết, liên doanh chưa chia'),
    sa.Column('gain_loss_on_derivatives_valuation', sa.Integer(), nullable=False, comment='12.7. Lãi, lỗ đánh giá công cụ phái sinh'),
    sa.Column('gain_loss_from_revaluation_of_fixed_assets', sa.Integer(), nullable=False, comment='12.8. Lãi, lỗ đánh giá lại tài sản cố định theo mô hình giá trị hợp lý'),
    sa.Column('total_comprehensive_income', sa.Integer(), nullable=False, comment='Tổng thu nhập toàn diện'),
    sa.Column('comprehensive_income_attributable_to_owners', sa.Integer(), nullable=False, comment='Thu nhập toàn diện phân bổ cho chủ sở hữu'),
    sa.Column('comprehensive_income_attributable_to_non_controlling_interests', sa.Integer(), nullable=False, comment='Thu nhập toàn diện phân bổ cho cổ đông không nắm quyền kiểm soát'),
    sa.Column('earnings_per_share', sa.Integer(), nullable=False, comment='XIII. THU NHẬP THUẦN TRÊN CỔ PHIẾU PHỔ THÔNG'),
    sa.Column('basic_earnings_per_share', sa.Float(), nullable=False, comment='13.1. Lãi cơ bản trên cổ phiếu (Đồng/1 cổ phiếu)'),
    sa.Column('diluted_earnings_per_share', sa.Float(), nullable=False, comment='13.2. Thu nhập pha loãng trên cổ phiếu (Đồng/1 cổ phiếu)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fs_income_statement_type_three_quarter'), 'fs_income_statement_type_three', ['quarter'], unique=False)
    op.create_index(op.f('ix_fs_income_statement_type_three_stock_id'), 'fs_income_statement_type_three', ['stock_id'], unique=False)
    op.create_index(op.f('ix_fs_income_statement_type_three_year'), 'fs_income_statement_type_three', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fs_income_statement_type_three_year'), table_name='fs_income_statement_type_three')
    op.drop_index(op.f('ix_fs_income_statement_type_three_stock_id'), table_name='fs_income_statement_type_three')
    op.drop_index(op.f('ix_fs_income_statement_type_three_quarter'), table_name='fs_income_statement_type_three')
    op.drop_table('fs_income_statement_type_three')
    # ### end Alembic commands ###
