"""create newspapper table

Revision ID: 896376c6a360
Revises: 88edbc44cdab
Create Date: 2026-05-28 09:14:08.907898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '896376c6a360'
down_revision: Union[str, Sequence[str], None] = '88edbc44cdab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fs_cash_flow_statement_type_one',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stock_id', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.String(length=10), nullable=False),
    sa.Column('operating_activities_section', sa.BigInteger(), nullable=False, comment='I. Lưu chuyển tiền từ hoạt động kinh doanh'),
    sa.Column('profit_before_tax', sa.BigInteger(), nullable=False, comment='1. Lợi nhuận trước thuế'),
    sa.Column('total_adjustments', sa.BigInteger(), nullable=False, comment='2. Điều chỉnh cho các khoản'),
    sa.Column('depreciation_of_fixed_assets', sa.BigInteger(), nullable=False, comment='Khấu hao TSCĐ'),
    sa.Column('provisions', sa.BigInteger(), nullable=False, comment='Các khoản dự phòng'),
    sa.Column('share_of_profit_from_associates', sa.BigInteger(), nullable=False, comment='Lợi nhuận thuần từ đầu tư vào công ty liên kết'),
    sa.Column('write_offs_of_fixed_assets', sa.BigInteger(), nullable=False, comment='Xóa sổ tài sản cố định (thuần)'),
    sa.Column('unrealized_foreign_exchange_changes', sa.BigInteger(), nullable=False, comment='Lãi, lỗ chênh lệch tỷ giá hối đoái chưa thực hiện'),
    sa.Column('gain_loss_from_disposal_of_fixed_assets', sa.BigInteger(), nullable=False, comment='Lãi, lỗ từ thanh lý TSCĐ'),
    sa.Column('gain_loss_from_investing_activities', sa.BigInteger(), nullable=False, comment='Lãi, lỗ từ hoạt động đầu tư'),
    sa.Column('interest_income_from_deposits', sa.BigInteger(), nullable=False, comment='Lãi tiền gửi'),
    sa.Column('interest_income', sa.BigInteger(), nullable=False, comment='Thu nhập lãi'),
    sa.Column('interest_expense', sa.BigInteger(), nullable=False, comment='Chi phí lãi vay'),
    sa.Column('direct_appropriations_from_profit', sa.BigInteger(), nullable=False, comment='Các khoản chi trực tiếp từ lợi nhuận'),
    sa.Column('operating_profit_before_working_capital_change', sa.BigInteger(), nullable=False, comment='3. Lợi nhuận từ hoạt động kinh doanh trước thay đổi vốn lưu động'),
    sa.Column('change_in_receivables', sa.BigInteger(), nullable=False, comment='Tăng, giảm các khoản phải thu'),
    sa.Column('change_in_inventory', sa.BigInteger(), nullable=False, comment='Tăng, giảm hàng tồn kho'),
    sa.Column('change_in_payables_excl_tax_and_interest', sa.BigInteger(), nullable=False, comment='Tăng, giảm các khoản phải trả (Không kể lãi vay phải trả, thuế thu nhập doanh nghiệp phải nộp)'),
    sa.Column('change_in_prepaid_expenses', sa.BigInteger(), nullable=False, comment='Tăng giảm chi phí trả trước'),
    sa.Column('change_in_other_current_assets', sa.BigInteger(), nullable=False, comment='Tăng giảm tài sản ngắn hạn khác'),
    sa.Column('interest_paid', sa.BigInteger(), nullable=False, comment='Tiền lãi vay phải trả'),
    sa.Column('corporate_income_tax_paid', sa.BigInteger(), nullable=False, comment='Thuế thu nhập doanh nghiệp đã nộp'),
    sa.Column('other_operating_cash_receipts', sa.BigInteger(), nullable=False, comment='Tiền thu khác từ hoạt động kinh doanh'),
    sa.Column('other_operating_cash_payments', sa.BigInteger(), nullable=False, comment='Tiền chi khác từ hoạt động kinh doanh'),
    sa.Column('net_cash_flows_from_operating_activities', sa.BigInteger(), nullable=False, comment='Lưu chuyển tiền thuần từ hoạt động kinh doanh'),
    sa.Column('investing_activities_section', sa.BigInteger(), nullable=False, comment='II. Lưu chuyển tiền từ hoạt động đầu tư'),
    sa.Column('cash_paid_for_fixed_assets', sa.BigInteger(), nullable=False, comment='1. Tiền chi để mua sắm, xây dựng TSCĐ và các tài sản dài hạn khác'),
    sa.Column('cash_received_from_disposal_of_fixed_assets', sa.BigInteger(), nullable=False, comment='2. Tiền thu từ thanh lý, nhượng bán TSCĐ và các tài sản dài hạn khác'),
    sa.Column('cash_paid_for_loans_and_debt_instruments', sa.BigInteger(), nullable=False, comment='3. Tiền chi cho vay, mua các công cụ nợ của đơn vị khác'),
    sa.Column('cash_received_from_loans_and_debt_instruments', sa.BigInteger(), nullable=False, comment='4. Tiền thu hồi cho vay, bán lại các công cụ nợ của các đơn vị khác'),
    sa.Column('investments_in_joint_ventures_and_associates', sa.BigInteger(), nullable=False, comment='5. Đầu tư góp vốn vào công ty liên doanh liên kết'),
    sa.Column('cash_paid_for_short_term_investments', sa.BigInteger(), nullable=False, comment='6. Chi đầu tư ngắn hạn'),
    sa.Column('cash_paid_for_equity_investments', sa.BigInteger(), nullable=False, comment='7. Tiền chi đầu tư góp vốn vào đơn vị khác'),
    sa.Column('cash_received_from_equity_investments', sa.BigInteger(), nullable=False, comment='8. Tiền thu hồi đầu tư góp vốn vào đơn vị khác'),
    sa.Column('interest_received_from_deposits', sa.BigInteger(), nullable=False, comment='9. Lãi tiền gửi đã thu'),
    sa.Column('interest_and_dividends_received', sa.BigInteger(), nullable=False, comment='10. Tiền thu lãi cho vay, cổ tức và lợi nhuận được chia'),
    sa.Column('cash_paid_to_buy_back_minority_interests', sa.BigInteger(), nullable=False, comment='11. Tiền chi mua lại phần vốn góp của các cổ đông thiểu số'),
    sa.Column('net_cash_flows_from_investing_activities', sa.BigInteger(), nullable=False, comment='Lưu chuyển tiền thuần từ hoạt động đầu tư'),
    sa.Column('financing_activities_section', sa.BigInteger(), nullable=False, comment='III. Lưu chuyển tiền từ hoạt động tài chính'),
    sa.Column('cash_received_from_issuing_shares', sa.BigInteger(), nullable=False, comment='1. Tiền thu từ phát hành cổ phiếu, nhận vốn góp của chủ sở hữu'),
    sa.Column('cash_paid_for_share_buybacks', sa.BigInteger(), nullable=False, comment='2. Tiền chi trả vốn góp cho các chủ sở hữu, mua lại cổ phiếu của doanh nghiệp đã phát hành'),
    sa.Column('cash_received_from_borrowings', sa.BigInteger(), nullable=False, comment='3. Tiền vay ngắn hạn, dài hạn nhận được'),
    sa.Column('cash_repayments_of_borrowings', sa.BigInteger(), nullable=False, comment='4. Tiền chi trả nợ gốc vay'),
    sa.Column('cash_repayments_of_finance_lease_liabilities', sa.BigInteger(), nullable=False, comment='5. Tiền chi trả nợ thuê tài chính'),
    sa.Column('other_financing_cash_payments', sa.BigInteger(), nullable=False, comment='6. Tiền chi khác từ hoạt động tài chính'),
    sa.Column('payments_for_privatization', sa.BigInteger(), nullable=False, comment='7. Tiền chi trả từ cổ phần hóa'),
    sa.Column('dividends_paid_to_owners', sa.BigInteger(), nullable=False, comment='8. Cổ tức, lợi nhuận đã trả cho chủ sở hữu'),
    sa.Column('minority_capital_contribution_into_subsidiaries', sa.BigInteger(), nullable=False, comment='9. Vốn góp của các cổ đông thiểu số vào các công ty con'),
    sa.Column('payments_for_welfare_and_social_funds', sa.BigInteger(), nullable=False, comment='10. Chi tiêu quỹ phúc lợi xã hội'),
    sa.Column('net_cash_flows_from_financing_activities', sa.BigInteger(), nullable=False, comment='Lưu chuyển tiền thuần từ hoạt động tài chính'),
    sa.Column('net_change_in_cash', sa.BigInteger(), nullable=False, comment='Lưu chuyển tiền thuần trong kỳ'),
    sa.Column('cash_and_cash_equivalents_at_start_of_period', sa.BigInteger(), nullable=False, comment='Tiền và tương đương tiền đầu kỳ'),
    sa.Column('effect_of_exchange_rate_changes', sa.BigInteger(), nullable=False, comment='Ảnh hưởng của thay đổi tỷ giá hối đoái quy đổi ngoại tệ'),
    sa.Column('cash_and_cash_equivalents_at_end_of_period', sa.BigInteger(), nullable=False, comment='Tiền và tương đương tiền cuối kỳ'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fs_cash_flow_statement_type_one_quarter'), 'fs_cash_flow_statement_type_one', ['quarter'], unique=False)
    op.create_index(op.f('ix_fs_cash_flow_statement_type_one_stock_id'), 'fs_cash_flow_statement_type_one', ['stock_id'], unique=False)
    op.create_index(op.f('ix_fs_cash_flow_statement_type_one_year'), 'fs_cash_flow_statement_type_one', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fs_cash_flow_statement_type_one_year'), table_name='fs_cash_flow_statement_type_one')
    op.drop_index(op.f('ix_fs_cash_flow_statement_type_one_stock_id'), table_name='fs_cash_flow_statement_type_one')
    op.drop_index(op.f('ix_fs_cash_flow_statement_type_one_quarter'), table_name='fs_cash_flow_statement_type_one')
    op.drop_table('fs_cash_flow_statement_type_one')
    # ### end Alembic commands ###
