"""create newspapper table

Revision ID: 8cdd4b205faf
Revises: 0c295d031872
Create Date: 2026-05-16 20:19:43.331583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cdd4b205faf'
down_revision: Union[str, Sequence[str], None] = '0c295d031872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newspaper', sa.Column('newspaper_content', sa.Text(), nullable=False))
    op.drop_column('newspaper', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newspaper', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('newspaper', 'newspaper_content')
    # ### end Alembic commands ###
