"""create newspapper table

Revision ID: c301750687fe
Revises: 293df394d024
Create Date: 2026-05-14 20:29:12.050336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c301750687fe'
down_revision: Union[str, Sequence[str], None] = '293df394d024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newspaper',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('publish_date', sa.Date(), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_newspaper_url_created_at'), table_name='newspaper_url')
    op.drop_index(op.f('ix_newspaper_url_newspaper_title'), table_name='newspaper_url')
    op.drop_index(op.f('ix_newspaper_url_source'), table_name='newspaper_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_newspaper_url_source'), 'newspaper_url', ['source'], unique=False)
    op.create_index(op.f('ix_newspaper_url_newspaper_title'), 'newspaper_url', ['newspaper_title'], unique=False)
    op.create_index(op.f('ix_newspaper_url_created_at'), 'newspaper_url', ['created_at'], unique=False)
    op.drop_table('newspaper')
    # ### end Alembic commands ###
