"""create new column

Revision ID: d27353a963e7
Revises: b800481a40a3
Create Date: 2026-07-18 11:13:26.189212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd27353a963e7'
down_revision: Union[str, Sequence[str], None] = 'b800481a40a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fs_financial_statistics_overview_type_four', sa.Column('is_load_to_qdrant', sa.Integer(), server_default='0', nullable=False))
    op.add_column('fs_financial_statistics_overview_type_one', sa.Column('is_load_to_qdrant', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fs_financial_statistics_overview_type_one', 'is_load_to_qdrant')
    op.drop_column('fs_financial_statistics_overview_type_four', 'is_load_to_qdrant')
    # ### end Alembic commands ###
