"""create newspapper table

Revision ID: dcca09c179cf
Revises: ecac771e711a
Create Date: 2026-05-28 14:01:20.827991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcca09c179cf'
down_revision: Union[str, Sequence[str], None] = 'ecac771e711a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fs_financial_statistics_overview',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stock_id', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.String(length=10), nullable=False),
    sa.Column('p_e', sa.Float(), nullable=False, comment='P/E'),
    sa.Column('p_s', sa.Float(), nullable=False, comment='P/S'),
    sa.Column('p_b', sa.Float(), nullable=False, comment='P/B'),
    sa.Column('eps', sa.Float(), nullable=False, comment='EPS'),
    sa.Column('net_profit_margin', sa.Float(), nullable=False, comment='Net Profit Margin'),
    sa.Column('yoea', sa.Float(), nullable=False, comment='YOE'),
    sa.Column('nim', sa.Float(), nullable=False, comment='NIM'),
    sa.Column('cof', sa.Float(), nullable=False, comment='COF'),
    sa.Column('lar', sa.Float(), nullable=False, comment='LAR'),
    sa.Column('ldr', sa.Float(), nullable=False, comment='LDR'),
    sa.Column('clr', sa.Float(), nullable=False, comment='CLR'),
    sa.Column('cta', sa.Float(), nullable=False, comment='CTA'),
    sa.Column('elr', sa.Float(), nullable=False, comment='ELR'),
    sa.Column('roa', sa.Float(), nullable=False, comment='ROA'),
    sa.Column('roe', sa.Float(), nullable=False, comment='ROE'),
    sa.Column('cir', sa.Float(), nullable=False, comment='CIR'),
    sa.Column('llrl', sa.Float(), nullable=False, comment='LLRL'),
    sa.Column('llrnpl', sa.Float(), nullable=False, comment='LLRNPL'),
    sa.Column('npl_ratio', sa.Float(), nullable=False, comment='NPL Ratio'),
    sa.Column('pcl', sa.Float(), nullable=False, comment='PCL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fs_financial_statistics_overview_quarter'), 'fs_financial_statistics_overview', ['quarter'], unique=False)
    op.create_index(op.f('ix_fs_financial_statistics_overview_stock_id'), 'fs_financial_statistics_overview', ['stock_id'], unique=False)
    op.create_index(op.f('ix_fs_financial_statistics_overview_year'), 'fs_financial_statistics_overview', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fs_financial_statistics_overview_year'), table_name='fs_financial_statistics_overview')
    op.drop_index(op.f('ix_fs_financial_statistics_overview_stock_id'), table_name='fs_financial_statistics_overview')
    op.drop_index(op.f('ix_fs_financial_statistics_overview_quarter'), table_name='fs_financial_statistics_overview')
    op.drop_table('fs_financial_statistics_overview')
    # ### end Alembic commands ###
