"""create newspapper table

Revision ID: df1368a39f58
Revises: 2c7e7c5fb265
Create Date: 2026-05-16 20:25:33.094334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df1368a39f58'
down_revision: Union[str, Sequence[str], None] = '2c7e7c5fb265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newspaper', sa.Column('newspaper_content', sa.Text(), nullable=True))
    op.drop_column('newspaper', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newspaper', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('newspaper', 'newspaper_content')
    # ### end Alembic commands ###
