"""create newspapper table

Revision ID: ecac771e711a
Revises: 9b242a567a38
Create Date: 2026-05-28 10:48:47.763417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecac771e711a'
down_revision: Union[str, Sequence[str], None] = '9b242a567a38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fs_cash_flow_statement_type_four',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stock_id', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.String(length=10), nullable=False),
    sa.Column('interest_and_similar_income_received', sa.Integer(), nullable=False, comment='Thu nhập lãi và các khoản thu nhập tương tự nhận được'),
    sa.Column('interest_and_similar_expenses_paid', sa.Integer(), nullable=False, comment='Chi phí lãi và các chi phí tương tự đã trả'),
    sa.Column('fee_and_commission_income_received', sa.Integer(), nullable=False, comment='Thu nhập từ hoạt động dịch vụ nhận được'),
    sa.Column('net_gain_loss_from_trading_activities', sa.Integer(), nullable=False, comment='Chênh lệch số tiền thực thu/ thực chi từ hoạt động kinh doanh (ngoại tệ, vàng bạc, chứng khoán)'),
    sa.Column('other_operating_income', sa.Integer(), nullable=False, comment='Thu nhập khác'),
    sa.Column('cash_recovered_from_bad_debts_written_off', sa.Integer(), nullable=False, comment='Tiền thu các khoản nợ đã được xử lý xóa, bù đắp bằng nguồn rủi ro'),
    sa.Column('cash_paid_to_employees_and_for_operating_expenses', sa.Integer(), nullable=False, comment='Tiền chi trả cho nhân viên và hoạt động quản lý, công vụ'),
    sa.Column('corporate_income_tax_paid', sa.Integer(), nullable=False, comment='Tiền thuế thu nhập thực nộp trong kỳ'),
    sa.Column('operating_cash_flows_before_working_capital_changes', sa.Integer(), nullable=False, comment='Lưu chuyển tiền thuần từ hoạt động kinh doanh trước những thay đổi về tài sản và vốn lưu động'),
    sa.Column('change_in_deposits_and_loans_to_other_cits', sa.Integer(), nullable=False, comment='(Tăng)/Giảm các khoản tiền, vàng gửi và cho vay các TCTD khác'),
    sa.Column('change_in_trading_securities', sa.Integer(), nullable=False, comment='(Tăng)/Giảm các khoản về kinh doanh chứng khoán'),
    sa.Column('change_in_derivative_financial_assets', sa.Integer(), nullable=False, comment='(Tăng)/Giảm các công cụ tài chính phái sinh và các tài sản tài chính khác'),
    sa.Column('change_in_loans_to_customers', sa.Integer(), nullable=False, comment='(Tăng)/Giảm các khoản cho vay khách hàng'),
    sa.Column('change_in_provisions_for_credit_losses', sa.Integer(), nullable=False, comment='(Tăng)/Giảm nguồn dự phòng để bù bắp tổn thất các khoản'),
    sa.Column('change_in_other_operating_assets', sa.Integer(), nullable=False, comment='(Tăng)/Giảm khác về tài sản hoạt động'),
    sa.Column('change_in_due_to_government_and_sbv', sa.Integer(), nullable=False, comment='Tăng/(Giảm) các khoản nợ chính phủ và NHNN'),
    sa.Column('change_in_deposits_and_borrowings_from_other_cits', sa.Integer(), nullable=False, comment='Tăng/(Giảm) các khoản tiền gửi, tiền vay các TCTD'),
    sa.Column('change_in_deposits_from_customers', sa.Integer(), nullable=False, comment='Tăng/(Giảm) tiền gửi của khách hàng'),
    sa.Column('change_in_valuable_papers_issued', sa.Integer(), nullable=False, comment='Tăng/(Giảm) phát hành giấy tờ có giá'),
    sa.Column('change_in_entrusted_funds_and_loans', sa.Integer(), nullable=False, comment='Tăng/(Giảm) vốn tài trợ, ủy thác đầu tư, cho vay mà TCTD chịu rủi ro'),
    sa.Column('change_in_derivative_financial_liabilities', sa.Integer(), nullable=False, comment='Tăng/(Giảm) các công cụ tài chính phái sinh và các khoản nợ tài chính khác'),
    sa.Column('change_in_other_operating_liabilities', sa.Integer(), nullable=False, comment='Tăng/(Giảm) khác về công nợ hoạt động'),
    sa.Column('payments_from_welfare_and_other_funds', sa.Integer(), nullable=False, comment='Chi từ các quỹ của TCTD'),
    sa.Column('net_cash_flows_from_operating_activities', sa.Integer(), nullable=False, comment='Lưu chuyển tiền thuần từ hoạt động kinh doanh'),
    sa.Column('cash_proceeds_from_disposal_of_subsidiaries', sa.Integer(), nullable=False, comment='Tiền giảm do bán công ty con'),
    sa.Column('cash_paid_for_fixed_assets', sa.Integer(), nullable=False, comment='Mua sắm TSCĐ'),
    sa.Column('cash_received_from_disposal_of_fixed_assets', sa.Integer(), nullable=False, comment='Tiền thu từ thanh lý, nhượng bán TSCĐ'),
    sa.Column('cash_paid_for_disposal_of_fixed_assets', sa.Integer(), nullable=False, comment='Tiền chi từ thanh lý, nhượng bán TSCĐ'),
    sa.Column('cash_paid_for_investment_properties', sa.Integer(), nullable=False, comment='Mua sắm bất động sản đầu tư'),
    sa.Column('cash_received_from_disposal_of_investment_properties', sa.Integer(), nullable=False, comment='Tiền thu từ bán, thanh lý bất động sản đầu tư'),
    sa.Column('cash_paid_for_disposal_of_investment_properties', sa.Integer(), nullable=False, comment='Tiền chi ra do bán, thanh lý bất động sản đầu tư'),
    sa.Column('cash_paid_for_equity_investments', sa.Integer(), nullable=False, comment='Tiền chi đầu tư, góp vốn vào các đơn vị khác'),
    sa.Column('cash_received_from_equity_investments', sa.Integer(), nullable=False, comment='Tiền thu đầu tư, góp vốn vào các đơn vị khác'),
    sa.Column('dividends_and_profits_received', sa.Integer(), nullable=False, comment='Tiền thu cổ tức và lợi nhuận được chia từ các khoản đầu tư, góp vốn dài hạn'),
    sa.Column('net_cash_flows_from_investing_activities', sa.Integer(), nullable=False, comment='Lưu chuyển tiền thuần từ hoạt động đầu tư'),
    sa.Column('cash_received_from_issuing_shares', sa.Integer(), nullable=False, comment='Tăng vốn cổ phần từ góp vốn và phát hành cổ phiếu'),
    sa.Column('cash_received_from_long_term_eligible_papers_and_loans', sa.Integer(), nullable=False, comment='Tiền thu từ phát hành giấy tờ có giá dài hạn có đủ điều kiện tính vào vốn tự có và các khoản vốn vay dài hạn khác'),
    sa.Column('cash_repayments_of_long_term_eligible_papers_and_loans', sa.Integer(), nullable=False, comment='Tiền chi thanh toán giấy tờ có giá dài hạn có đủ điều kiện tính vào vốn tự có và các khoản vốn vay dài hạn khác'),
    sa.Column('dividends_paid_to_shareholders', sa.Integer(), nullable=False, comment='Cổ tức trả cho cổ đông, lợi nhuận đã chia'),
    sa.Column('cash_paid_for_treasury_shares_buyback', sa.Integer(), nullable=False, comment='Tiền chi ra mua cổ phiếu ngân quỹ'),
    sa.Column('cash_received_from_disposal_of_treasury_shares', sa.Integer(), nullable=False, comment='Tiền thu được do bán cổ phiếu ngân quỹ'),
    sa.Column('net_cash_flows_from_financing_activities', sa.Integer(), nullable=False, comment='Lưu chuyển tiền từ hoạt động tài chính'),
    sa.Column('net_change_in_cash', sa.Integer(), nullable=False, comment='Lưu chuyển tiền thuần trong kỳ'),
    sa.Column('cash_and_cash_equivalents_at_start_of_period', sa.Integer(), nullable=False, comment='Tiền và tương đương tiền đầu kỳ'),
    sa.Column('effect_of_exchange_rate_changes', sa.Integer(), nullable=False, comment='Ảnh hưởng của thay đổi tỷ giá hối đoái quy đổi ngoại tệ'),
    sa.Column('cash_and_cash_equivalents_at_end_of_period', sa.Integer(), nullable=False, comment='Tiền và tương đương tiền cuối kỳ'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fs_cash_flow_statement_type_four_quarter'), 'fs_cash_flow_statement_type_four', ['quarter'], unique=False)
    op.create_index(op.f('ix_fs_cash_flow_statement_type_four_stock_id'), 'fs_cash_flow_statement_type_four', ['stock_id'], unique=False)
    op.create_index(op.f('ix_fs_cash_flow_statement_type_four_year'), 'fs_cash_flow_statement_type_four', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fs_cash_flow_statement_type_four_year'), table_name='fs_cash_flow_statement_type_four')
    op.drop_index(op.f('ix_fs_cash_flow_statement_type_four_stock_id'), table_name='fs_cash_flow_statement_type_four')
    op.drop_index(op.f('ix_fs_cash_flow_statement_type_four_quarter'), table_name='fs_cash_flow_statement_type_four')
    op.drop_table('fs_cash_flow_statement_type_four')
    # ### end Alembic commands ###
