"""create newspapper table

Revision ID: ee1b92562323
Revises: 27bc36b34579
Create Date: 2026-05-17 09:58:31.172073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee1b92562323'
down_revision: Union[str, Sequence[str], None] = '27bc36b34579'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newspaper',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('newspaper_title', sa.Text(), nullable=False),
    sa.Column('newspaper_url', sa.String(length=255), nullable=False),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('newspaper_content', sa.Text(), nullable=True),
    sa.Column('newspaper_summary', sa.Text(), nullable=False),
    sa.Column('is_load_to_qdrant', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('newspaper')
    # ### end Alembic commands ###
