"""create newspapper table

Revision ID: eff379c29b5c
Revises: d1c847d4aed9
Create Date: 2026-05-16 20:34:23.278126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eff379c29b5c'
down_revision: Union[str, Sequence[str], None] = 'd1c847d4aed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('newspaper')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newspaper',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('newspaper_title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('newspaper_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('publish_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('newspaper_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('newspaper_summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_embedded', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('newspaper_pkey'))
    )
    # ### end Alembic commands ###
