"""create newcolumns

Revision ID: f168692c65f2
Revises: 15b2d9d58a30
Create Date: 2026-07-17 19:47:29.671239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f168692c65f2'
down_revision: Union[str, Sequence[str], None] = '15b2d9d58a30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'fs_balance_sheet_type_four',
        sa.Column(
            'is_load_to_qdrant',
            sa.Integer(),
            nullable=False,
            server_default=sa.text('0'),
        ),
    )
    op.alter_column('fs_balance_sheet_type_four', 'is_load_to_qdrant', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fs_balance_sheet_type_four', 'is_load_to_qdrant')
    # ### end Alembic commands ###
