"""create kqkd table

Revision ID: f292cbc65ab8
Revises: ee1b92562323
Create Date: 2026-05-25 20:11:44.377398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f292cbc65ab8'
down_revision: Union[str, Sequence[str], None] = 'ee1b92562323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income_statement_type1',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('gross_revenue', sa.Integer(), nullable=False, comment='1. Tổng doanh thu hoạt động kinh doanh'),
    sa.Column('revenue_deductions', sa.Integer(), nullable=False, comment='2. Các khoản giảm trừ doanh thu'),
    sa.Column('net_revenue', sa.Integer(), nullable=False, comment='3. Doanh thu thuần (1)-(2)'),
    sa.Column('cost_of_goods_sold', sa.Integer(), nullable=False, comment='4. Giá vốn hàng bán'),
    sa.Column('gross_profit', sa.Integer(), nullable=False, comment='5. Lợi nhuận gộp (3)-(4)'),
    sa.Column('financial_income', sa.Integer(), nullable=False, comment='6. Doanh thu hoạt động tài chính'),
    sa.Column('financial_expenses', sa.Integer(), nullable=False, comment='7. Chi phí tài chính'),
    sa.Column('interest_expense', sa.Integer(), nullable=False, comment='Trong đó: Chi phí lãi vay'),
    sa.Column('jv_associates_profit', sa.Integer(), nullable=False, comment='8. Phần lợi nhuận hoặc lỗ trong công ty liên kết liên doanh'),
    sa.Column('selling_expenses', sa.Integer(), nullable=False, comment='9. Chi phí bán hàng'),
    sa.Column('general_and_administrative_expenses', sa.Integer(), nullable=False, comment='10. Chi phí quản lý doanh nghiệp'),
    sa.Column('net_operating_profit', sa.Integer(), nullable=False, comment='11. Lợi nhuận thuần từ hoạt động kinh doanh (5)+(6)-(7)+(8)-(9)-(10)'),
    sa.Column('other_income', sa.Integer(), nullable=False, comment='12. Thu nhập khác'),
    sa.Column('other_expenses', sa.Integer(), nullable=False, comment='13. Chi phí khác'),
    sa.Column('other_profit', sa.Integer(), nullable=False, comment='14. Lợi nhuận khác (12)-(13)'),
    sa.Column('total_accounting_profit_before_tax', sa.Integer(), nullable=False, comment='15. Tổng lợi nhuận kế toán trước thuế (11)+(14)'),
    sa.Column('current_corporate_income_tax_expense', sa.Integer(), nullable=False, comment='16. Chi phí thuế TNDN hiện hành'),
    sa.Column('deferred_corporate_income_tax_expense', sa.Integer(), nullable=False, comment='17. Chi phí thuế TNDN hoãn lại'),
    sa.Column('corporate_income_tax_expense', sa.Integer(), nullable=False, comment='18. Chi phí thuế TNDN (16)+(17)'),
    sa.Column('net_profit_after_corporate_income_tax', sa.Integer(), nullable=False, comment='19. Lợi nhuận sau thuế thu nhập doanh nghiệp (15)-(18)'),
    sa.Column('non_controlling_interests', sa.Integer(), nullable=False, comment='20. Lợi nhuận sau thuế của cổ đông không kiểm soát'),
    sa.Column('net_profit_parent', sa.Integer(), nullable=False, comment='21. Lợi nhuận sau thuế của cổ đông của công ty mẹ (19)-(20)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_income_statement_type1_quarter'), 'income_statement_type1', ['quarter'], unique=False)
    op.create_index(op.f('ix_income_statement_type1_year'), 'income_statement_type1', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_income_statement_type1_year'), table_name='income_statement_type1')
    op.drop_index(op.f('ix_income_statement_type1_quarter'), table_name='income_statement_type1')
    op.drop_table('income_statement_type1')
    # ### end Alembic commands ###
