"""create newspapper table

Revision ID: f8ac8cc482c1
Revises: c301750687fe
Create Date: 2026-05-14 20:50:06.017780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8ac8cc482c1'
down_revision: Union[str, Sequence[str], None] = 'c301750687fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newspaper', sa.Column('is_embedded', sa.Integer(), nullable=False))
    op.add_column('newspaper', sa.Column('created_at', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('newspaper', 'created_at')
    op.drop_column('newspaper', 'is_embedded')
    # ### end Alembic commands ###
