"""init tables

Revision ID: fde6c78b19f6
Revises: 2886f0ebbb5d
Create Date: 2026-03-05 18:28:04.190322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fde6c78b19f6'
down_revision: Union[str, Sequence[str], None] = '2886f0ebbb5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fund_nav_business_sector'), table_name='fund_nav')
    op.drop_index(op.f('ix_fund_nav_fund_id'), table_name='fund_nav')
    op.drop_index(op.f('ix_fund_nav_stock_id'), table_name='fund_nav')
    op.drop_table('fund_nav')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fund_nav',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('fund_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('stock_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('business_sector', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('gav', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('fund_nav_pkey'))
    )
    op.create_index(op.f('ix_fund_nav_stock_id'), 'fund_nav', ['stock_id'], unique=False)
    op.create_index(op.f('ix_fund_nav_fund_id'), 'fund_nav', ['fund_id'], unique=False)
    op.create_index(op.f('ix_fund_nav_business_sector'), 'fund_nav', ['business_sector'], unique=False)
    # ### end Alembic commands ###
