kind: newspaper_url

urls:
  - vietstock:
    - 'https://vietstock.vn/chung-khoan.htm'
  - cafef:
    - https://cafef.vn/thi-truong-chung-khoan.chn
    - https://cafef.vn/tai-chinh-ngan-hang.chn
    - https://cafef.vn/doanh-nghiep.chn
  - thoibaotaichinhvietnam:
    - https://thoibaotaichinhvietnam.vn/chung-khoan
