kind: stock_price

urls:
  - ban_le_chuyen_dung:
    - https://simplize.vn/co-phieu/MWG/lich-su-gia
    - https://simplize.vn/co-phieu/PNJ/lich-su-gia
    - https://simplize.vn/co-phieu/FRT/lich-su-gia
    - https://simplize.vn/co-phieu/DGW/lich-su-gia
  - bao_hiem:
    - https://simplize.vn/co-phieu/BVH/lich-su-gia
    - https://simplize.vn/co-phieu/PVI/lich-su-gia
  - chung_khoan_ngan_hang_dau_tu:
    - https://simplize.vn/co-phieu/TCX/lich-su-gia
    - https://simplize.vn/co-phieu/SSI/lich-su-gia
    - https://simplize.vn/co-phieu/VCK/lich-su-gia
    - https://simplize.vn/co-phieu/VPX/lich-su-gia
    - https://simplize.vn/co-phieu/VIX/lich-su-gia
    - https://simplize.vn/co-phieu/VCI/lich-su-gia
    - https://simplize.vn/co-phieu/VND/lich-su-gia
    - https://simplize.vn/co-phieu/HCM/lich-su-gia
    - https://simplize.vn/co-phieu/MBS/lich-su-gia
    - https://simplize.vn/co-phieu/SHS/lich-su-gia
    - https://simplize.vn/co-phieu/DSE/lich-su-gia
  - co_so_ha_tang_giao_thong_van_tai:
    - https://simplize.vn/co-phieu/ACV/lich-su-gia
    - https://simplize.vn/co-phieu/GMD/lich-su-gia
    - https://simplize.vn/co-phieu/PHP/lich-su-gia
    - https://simplize.vn/co-phieu/CII/lich-su-gia
    - https://simplize.vn/co-phieu/HAH/lich-su-gia
  - duoc_pham:
    - https://simplize.vn/co-phieu/DHG/lich-su-gia
    - https://simplize.vn/co-phieu/IMP/lich-su-gia
    - https://simplize.vn/co-phieu/DCL/lich-su-gia
  - dau_va_khi_dot:
    - https://simplize.vn/co-phieu/GAS/lich-su-gia
    - https://simplize.vn/co-phieu/BSR/lich-su-gia
    - https://simplize.vn/co-phieu/PLX/lich-su-gia
    - https://simplize.vn/co-phieu/OIL/lich-su-gia
  - det_may:
    - https://simplize.vn/co-phieu/VGT/lich-su-gia
    - https://simplize.vn/co-phieu/MSH/lich-su-gia
    - https://simplize.vn/co-phieu/TNG/lich-su-gia
    - https://simplize.vn/co-phieu/TCM/lich-su-gia
    - https://simplize.vn/co-phieu/PPH/lich-su-gia
    - https://simplize.vn/co-phieu/STK/lich-su-gia
    - https://simplize.vn/co-phieu/HTG/lich-su-gia
    - https://simplize.vn/co-phieu/GIL/lich-su-gia
  - dich_vu_vien_thong:
    - https://simplize.vn/co-phieu/VGI/lich-su-gia
    - https://simplize.vn/co-phieu/FOX/lich-su-gia
  - dich_vu_va_thiet_bi_dau_khi:
    - https://simplize.vn/co-phieu/PVS/lich-su-gia
    - https://simplize.vn/co-phieu/PVD/lich-su-gia
    - https://simplize.vn/co-phieu/PVT/lich-su-gia
    - https://simplize.vn/co-phieu/TOS/lich-su-gia
  - hoa_chat:
    - https://simplize.vn/co-phieu/DGC/lich-su-gia
    - https://simplize.vn/co-phieu/DCM/lich-su-gia
    - https://simplize.vn/co-phieu/DPM/lich-su-gia
  - hop_dung_bao_bi:
    - https://simplize.vn/co-phieu/ECO/lich-su-gia
    - https://simplize.vn/co-phieu/DHC/lich-su-gia
    - https://simplize.vn/co-phieu/AAA/lich-su-gia
    - https://simplize.vn/co-phieu/TDP/lich-su-gia
    - https://simplize.vn/co-phieu/MZG/lich-su-gia
  - kim_loai_va_khai_khoang:
    - https://simplize.vn/co-phieu/HPG/lich-su-gia
    - https://simplize.vn/co-phieu/MSR/lich-su-gia
    - https://simplize.vn/co-phieu/KSV/lich-su-gia
    - https://simplize.vn/co-phieu/HSG/lich-su-gia
  - may_moc_thiet_bi_nang_dong_tau:
    - https://simplize.vn/co-phieu/GEE/lich-su-gia
    - https://simplize.vn/co-phieu/VEA/lich-su-gia
    - https://simplize.vn/co-phieu/GEX/lich-su-gia
  - phan_mem_dich_vu_cntt:
    - https://simplize.vn/co-phieu/FPT/lich-su-gia
    - https://simplize.vn/co-phieu/CMG/lich-su-gia
  - quan_ly_phat_trien_bat_dong_san:
    - https://simplize.vn/co-phieu/KSF/lich-su-gia
    - https://simplize.vn/co-phieu/BCM/lich-su-gia
    - https://simplize.vn/co-phieu/VRE/lich-su-gia
    - https://simplize.vn/co-phieu/KBC/lich-su-gia
    - https://simplize.vn/co-phieu/KDH/lich-su-gia
    - https://simplize.vn/co-phieu/NVL/lich-su-gia
    - https://simplize.vn/co-phieu/VPI/lich-su-gia
    - https://simplize.vn/co-phieu/IDC/lich-su-gia
    - https://simplize.vn/co-phieu/DXG/lich-su-gia
    - https://simplize.vn/co-phieu/PDR/lich-su-gia
    - https://simplize.vn/co-phieu/TAL/lich-su-gia
    - https://simplize.vn/co-phieu/SJS/lich-su-gia
    - https://simplize.vn/co-phieu/SIP/lich-su-gia
    - https://simplize.vn/co-phieu/NLG/lich-su-gia
  - thuc_pham_va_thuoc_la:
    - https://simplize.vn/co-phieu/VNM/lich-su-gia
    - https://simplize.vn/co-phieu/MSN/lich-su-gia
    - https://simplize.vn/co-phieu/SBT/lich-su-gia
    - https://simplize.vn/co-phieu/HAG/lich-su-gia
    - https://simplize.vn/co-phieu/QNS/lich-su-gia
    - https://simplize.vn/co-phieu/VSF/lich-su-gia
    - https://simplize.vn/co-phieu/KDC/lich-su-gia
    - https://simplize.vn/co-phieu/VHC/lich-su-gia
    - https://simplize.vn/co-phieu/HPA/lich-su-gia
    - https://simplize.vn/co-phieu/MML/lich-su-gia
    - https://simplize.vn/co-phieu/BAF/lich-su-gia
    - https://simplize.vn/co-phieu/DBC/lich-su-gia
    - https://simplize.vn/co-phieu/AIG/lich-su-gia
    - https://simplize.vn/co-phieu/PAN/lich-su-gia
  - tien_ich_dien_san_xuat_dien:
    - https://simplize.vn/co-phieu/POW/lich-su-gia
    - https://simplize.vn/co-phieu/REE/lich-su-gia
    - https://simplize.vn/co-phieu/PGV/lich-su-gia
    - https://simplize.vn/co-phieu/VSH/lich-su-gia
    - https://simplize.vn/co-phieu/DTK/lich-su-gia
    - https://simplize.vn/co-phieu/NT2/lich-su-gia
  - tai_chinh_ngan_hang:
    - https://simplize.vn/co-phieu/VCB/lich-su-gia
    - https://simplize.vn/co-phieu/BID/lich-su-gia
    - https://simplize.vn/co-phieu/CTG/lich-su-gia
    - https://simplize.vn/co-phieu/TCB/lich-su-gia
    - https://simplize.vn/co-phieu/MBB/lich-su-gia
    - https://simplize.vn/co-phieu/VPB/lich-su-gia
    - https://simplize.vn/co-phieu/HDB/lich-su-gia
    - https://simplize.vn/co-phieu/STB/lich-su-gia
    - https://simplize.vn/co-phieu/LPB/lich-su-gia
    - https://simplize.vn/co-phieu/ACB/lich-su-gia
  - van_chuyen_hanh_khach:
    - https://simplize.vn/co-phieu/VJC/lich-su-gia
    - https://simplize.vn/co-phieu/HVN/lich-su-gia
  - vat_lieu_xay_dung:
    - https://simplize.vn/co-phieu/HT1/lich-su-gia
  - xay_dung:
    - https://simplize.vn/co-phieu/HUT/lich-su-gia
    - https://simplize.vn/co-phieu/VCG/lich-su-gia
    - https://simplize.vn/co-phieu/PC1/lich-su-gia
    - https://simplize.vn/co-phieu/CTR/lich-su-gia
    - https://simplize.vn/co-phieu/CTD/lich-su-gia
  - xay_dung_va_vat_lieu_xay_dung_dan_dung:
    - https://simplize.vn/co-phieu/VGC/lich-su-gia
    - https://simplize.vn/co-phieu/BMP/lich-su-gia
    - https://simplize.vn/co-phieu/NTP/lich-su-gia
    - https://simplize.vn/co-phieu/VCS/lich-su-gia
  - o_to_va_phu_tung_o_to:
    - https://simplize.vn/co-phieu/GVR/lich-su-gia
    - https://simplize.vn/co-phieu/TCH/lich-su-gia
    - https://simplize.vn/co-phieu/PHR/lich-su-gia
    - https://simplize.vn/co-phieu/HHS/lich-su-gia
    - https://simplize.vn/co-phieu/DPR/lich-su-gia
    - https://simplize.vn/co-phieu/VVS/lich-su-gia
    - https://simplize.vn/co-phieu/DRC/lich-su-gia
    - https://simplize.vn/co-phieu/TRC/lich-su-gia
  
