
data_type: finance_statement
kind: cash_flow_statement_type_one

urls:
  - https://fireant.vn/ma-chung-khoan/MWG
  - https://fireant.vn/ma-chung-khoan/PNJ
  - https://fireant.vn/ma-chung-khoan/FRT
  - https://fireant.vn/ma-chung-khoan/DGW
  - https://fireant.vn/ma-chung-khoan/PVI
  - https://fireant.vn/ma-chung-khoan/ACV
  - https://fireant.vn/ma-chung-khoan/GMD
  - https://fireant.vn/ma-chung-khoan/PHP
  - https://fireant.vn/ma-chung-khoan/CII
  - https://fireant.vn/ma-chung-khoan/HAH
  - https://fireant.vn/ma-chung-khoan/DHG
  - https://fireant.vn/ma-chung-khoan/IMP
  - https://fireant.vn/ma-chung-khoan/DCL
  - https://fireant.vn/ma-chung-khoan/GAS
  - https://fireant.vn/ma-chung-khoan/BSR
  - https://fireant.vn/ma-chung-khoan/PXL
  - https://fireant.vn/ma-chung-khoan/OIL
  - https://fireant.vn/ma-chung-khoan/VGT
  - https://fireant.vn/ma-chung-khoan/MSH
  - https://fireant.vn/ma-chung-khoan/TCM
  - https://fireant.vn/ma-chung-khoan/HTG
  - https://fireant.vn/ma-chung-khoan/GIL
  - https://fireant.vn/ma-chung-khoan/VGI
  - https://fireant.vn/ma-chung-khoan/FOX
  - https://fireant.vn/ma-chung-khoan/PVS
  - https://fireant.vn/ma-chung-khoan/PVD
  - https://fireant.vn/ma-chung-khoan/PVT
  - https://fireant.vn/ma-chung-khoan/DGC
  - https://fireant.vn/ma-chung-khoan/DCM
  - https://fireant.vn/ma-chung-khoan/DPM
  - https://fireant.vn/ma-chung-khoan/AAA
  - https://fireant.vn/ma-chung-khoan/TDP
  - https://fireant.vn/ma-chung-khoan/MZG
  - https://fireant.vn/ma-chung-khoan/HPG
  - https://fireant.vn/ma-chung-khoan/MSR
  - https://fireant.vn/ma-chung-khoan/KSV
  - https://fireant.vn/ma-chung-khoan/HSG
  - https://fireant.vn/ma-chung-khoan/GEE
  - https://fireant.vn/ma-chung-khoan/VEA
  - https://fireant.vn/ma-chung-khoan/GEX
  - https://fireant.vn/ma-chung-khoan/FPT
  - https://fireant.vn/ma-chung-khoan/CMG
  - https://fireant.vn/ma-chung-khoan/KSF
  - https://fireant.vn/ma-chung-khoan/BCM
  - https://fireant.vn/ma-chung-khoan/VRE
  - https://fireant.vn/ma-chung-khoan/KBC
  - https://fireant.vn/ma-chung-khoan/KDH
  - https://fireant.vn/ma-chung-khoan/NVL
  - https://fireant.vn/ma-chung-khoan/VPI
  - https://fireant.vn/ma-chung-khoan/IDC
  - https://fireant.vn/ma-chung-khoan/PDR
  - https://fireant.vn/ma-chung-khoan/TAL
  - https://fireant.vn/ma-chung-khoan/SIP
  - https://fireant.vn/ma-chung-khoan/NLG
  - https://fireant.vn/ma-chung-khoan/VNM
  - https://fireant.vn/ma-chung-khoan/MSN
  - https://fireant.vn/ma-chung-khoan/SBT
  - https://fireant.vn/ma-chung-khoan/HAG
  - https://fireant.vn/ma-chung-khoan/QNS
  - https://fireant.vn/ma-chung-khoan/VSF
  - https://fireant.vn/ma-chung-khoan/KDC
  - https://fireant.vn/ma-chung-khoan/VHC
  - https://fireant.vn/ma-chung-khoan/HPA
  - https://fireant.vn/ma-chung-khoan/MML
  - https://fireant.vn/ma-chung-khoan/BAF
  - https://fireant.vn/ma-chung-khoan/DBC
  - https://fireant.vn/ma-chung-khoan/PAN
  - https://fireant.vn/ma-chung-khoan/POW
  - https://fireant.vn/ma-chung-khoan/REE
  - https://fireant.vn/ma-chung-khoan/NT2
  - https://fireant.vn/ma-chung-khoan/VJC
  - https://fireant.vn/ma-chung-khoan/HVN
  - https://fireant.vn/ma-chung-khoan/HT1
  - https://fireant.vn/ma-chung-khoan/HUT
  - https://fireant.vn/ma-chung-khoan/VCG
  - https://fireant.vn/ma-chung-khoan/PC1
  - https://fireant.vn/ma-chung-khoan/CTR
  - https://fireant.vn/ma-chung-khoan/CTD
  - https://fireant.vn/ma-chung-khoan/VGC
  - https://fireant.vn/ma-chung-khoan/BMP
  - https://fireant.vn/ma-chung-khoan/NTP
  - https://fireant.vn/ma-chung-khoan/VCS
  - https://fireant.vn/ma-chung-khoan/GVR
  - https://fireant.vn/ma-chung-khoan/TCH
  - https://fireant.vn/ma-chung-khoan/PHR
  - https://fireant.vn/ma-chung-khoan/HHS
  - https://fireant.vn/ma-chung-khoan/DPR
  - https://fireant.vn/ma-chung-khoan/VVS
  - https://fireant.vn/ma-chung-khoan/TRC
  - https://fireant.vn/ma-chung-khoan/DXG

