urls:
  - tai_chinh_ngan_hang
    - https://simplize.vn/co-phieu/VCB/lich-su-gia
    - https://simplize.vn/co-phieu/BID/lich-su-gia#lich_su_gia_co_phieu
    - https://simplize.vn/co-phieu/CTG/lich-su-gia
    - https://simplize.vn/co-phieu/TCB/lich-su-gia
    - https://simplize.vn/co-phieu/MBB/lich-su-gia
    - https://simplize.vn/co-phieu/VPB/lich-su-gia
    - https://simplize.vn/co-phieu/HDB/lich-su-gia
    - https://simplize.vn/co-phieu/STB/lich-su-gia
    - https://simplize.vn/co-phieu/LPB/lich-su-gia
    - https://simplize.vn/co-phieu/ACB/lich-su-gia
  - chung_khoan_ngan_hang_dau_tu
    - https://simplize.vn/co-phieu/TCX/lich-su-gia
    - https://simplize.vn/co-phieu/SSI/lich-su-gia#lich_su_gia_co_phieu
    - https://simplize.vn/co-phieu/VCK/lich-su-gia
    - https://simplize.vn/co-phieu/VPX/lich-su-gia
    - https://simplize.vn/co-phieu/VIX/lich-su-gia
    - https://simplize.vn/co-phieu/VCI/lich-su-gia
    - https://simplize.vn/co-phieu/VND/lich-su-gia
    - https://simplize.vn/co-phieu/HCM/lich-su-gia
    - https://simplize.vn/co-phieu/MBS/lich-su-gia
    - https://simplize.vn/co-phieu/SHS/lich-su-gia
  - bao_hiem
    - https://simplize.vn/co-phieu/BVH/lich-su-gia
    - https://simplize.vn/co-phieu/PVI/lich-su-gia
    - https://simplize.vn/co-phieu/BIC/lich-su-gia
    - https://simplize.vn/co-phieu/VNR/lich-su-gia
    - https://simplize.vn/co-phieu/MIG/lich-su-gia
    - https://simplize.vn/co-phieu/PTI/lich-su-gia
    - https://simplize.vn/co-phieu/BMI/lich-su-gia
    - https://simplize.vn/co-phieu/PRE/lich-su-gia
    - https://simplize.vn/co-phieu/PGI/lich-su-gia
    - https://simplize.vn/co-phieu/ABI/lich-su-gia
  - bat_dong_san
    - https://simplize.vn/co-phieu/KSF/lich-su-gia
    - https://simplize.vn/co-phieu/BCM/lich-su-gia
    - https://simplize.vn/co-phieu/SSH/lich-su-gia
    - https://simplize.vn/co-phieu/CEO/lich-su-gia
    - https://simplize.vn/co-phieu/KDH/lich-su-gia
    - https://simplize.vn/co-phieu/NVL/lich-su-gia
    - https://simplize.vn/co-phieu/VPI/lich-su-gia
    - https://simplize.vn/co-phieu/IDC/lich-su-gia
    - https://simplize.vn/co-phieu/DXG/lich-su-gia
    - https://simplize.vn/co-phieu/PDR/lich-su-gia
    - https://simplize.vn/co-phieu/TAL/lich-su-gia
    - https://simplize.vn/co-phieu/SJS/lich-su-gia
    - https://simplize.vn/co-phieu/NLG/lich-su-gia
    - https://simplize.vn/co-phieu/HDG/lich-su-gia
  - co_so_ha_tang_va_giao_thong_van_tai
    - https://simplize.vn/co-phieu/ACV/lich-su-gia
    - https://simplize.vn/co-phieu/GMD/lich-su-gia
    - https://simplize.vn/co-phieu/PHP/lich-su-gia
    - https://simplize.vn/co-phieu/CII/lich-su-gia
    - https://simplize.vn/co-phieu/HAH/lich-su-gia
    - https://simplize.vn/co-phieu/VSC/lich-su-gia
    - https://simplize.vn/co-phieu/PDN/lich-su-gia
    - https://simplize.vn/co-phieu/HHV/lich-su-gia
    - https://simplize.vn/co-phieu/PAP/lich-su-gia
    - https://simplize.vn/co-phieu/SCS/lich-su-gia
  - van_chuyen_hanh_khach
    - https://simplize.vn/co-phieu/VJC/lich-su-gia
    - https://simplize.vn/co-phieu/HVN/lich-su-gia
    - https://simplize.vn/co-phieu/TRV/lich-su-gia
    - https://simplize.vn/co-phieu/BSG/lich-su-gia
    - https://simplize.vn/co-phieu/DL1/lich-su-gia
    - https://simplize.vn/co-phieu/SKG/lich-su-gia
    - https://simplize.vn/co-phieu/VNS/lich-su-gia
    - https://simplize.vn/co-phieu/PCT/lich-su-gia
    - https://simplize.vn/co-phieu/TCT/lich-su-gia
    - https://simplize.vn/co-phieu/PTT/lich-su-gia
  - xay_dung
    - https://simplize.vn/co-phieu/HUT/lich-su-gia
    - https://simplize.vn/co-phieu/VCG/lich-su-gia
    - https://simplize.vn/co-phieu/CC1/lich-su-gia
    - https://simplize.vn/co-phieu/LGC/lich-su-gia
    - https://simplize.vn/co-phieu/PC1/lich-su-gia
    - https://simplize.vn/co-phieu/SJG/lich-su-gia
    - https://simplize.vn/co-phieu/CTR/lich-su-gia
    - https://simplize.vn/co-phieu/CTD/lich-su-gia
    - https://simplize.vn/co-phieu/SCG/lich-su-gia
    - https://simplize.vn/co-phieu/DPG/lich-su-gia