"""create newspapper table

Revision ID: 0c295d031872
Revises: 32f41ddd7afd
Create Date: 2026-05-14 21:28:01.221239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c295d031872'
down_revision: Union[str, Sequence[str], None] = '32f41ddd7afd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('newspaper', 'publish_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('newspaper', 'publish_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
