"""recreate vn index table

Revision ID: 0db405352ec8
Revises: 4ebca58317a3
Create Date: 2026-05-14 13:38:58.638256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0db405352ec8'
down_revision: Union[str, Sequence[str], None] = '4ebca58317a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_newspaper_url_created_at'), table_name='newspaper_url')
    op.drop_index(op.f('ix_newspaper_url_newspaper_title'), table_name='newspaper_url')
    op.drop_index(op.f('ix_newspaper_url_newspaper_url'), table_name='newspaper_url')
    op.drop_index(op.f('ix_newspaper_url_source'), table_name='newspaper_url')
    op.drop_table('newspaper_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newspaper_url',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('newspaper_title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('newspaper_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_crawled', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('newspaper_url_pkey'))
    )
    op.create_index(op.f('ix_newspaper_url_source'), 'newspaper_url', ['source'], unique=False)
    op.create_index(op.f('ix_newspaper_url_newspaper_url'), 'newspaper_url', ['newspaper_url'], unique=False)
    op.create_index(op.f('ix_newspaper_url_newspaper_title'), 'newspaper_url', ['newspaper_title'], unique=False)
    op.create_index(op.f('ix_newspaper_url_created_at'), 'newspaper_url', ['created_at'], unique=False)
    # ### end Alembic commands ###
