"""create newspapper table

Revision ID: 27bc36b34579
Revises: 719cc14aba33
Create Date: 2026-05-17 09:58:08.362567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27bc36b34579'
down_revision: Union[str, Sequence[str], None] = '719cc14aba33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('newspaper')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newspaper',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('newspaper_title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('newspaper_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('publish_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('newspaper_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('newspaper_summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_load_to_qrant', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('newspaper_pkey'))
    )
    # ### end Alembic commands ###
