"""recreate vn index table

Revision ID: 293df394d024
Revises: 0db405352ec8
Create Date: 2026-05-14 15:43:50.771805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '293df394d024'
down_revision: Union[str, Sequence[str], None] = '0db405352ec8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newspaper_url',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('newspaper_title', sa.String(length=255), nullable=False),
    sa.Column('newspaper_url', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('is_crawled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newspaper_url_created_at'), 'newspaper_url', ['created_at'], unique=False)
    op.create_index(op.f('ix_newspaper_url_newspaper_title'), 'newspaper_url', ['newspaper_title'], unique=False)
    op.create_index(op.f('ix_newspaper_url_newspaper_url'), 'newspaper_url', ['newspaper_url'], unique=False)
    op.create_index(op.f('ix_newspaper_url_source'), 'newspaper_url', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_newspaper_url_source'), table_name='newspaper_url')
    op.drop_index(op.f('ix_newspaper_url_newspaper_url'), table_name='newspaper_url')
    op.drop_index(op.f('ix_newspaper_url_newspaper_title'), table_name='newspaper_url')
    op.drop_index(op.f('ix_newspaper_url_created_at'), table_name='newspaper_url')
    op.drop_table('newspaper_url')
    # ### end Alembic commands ###
