"""create vn-index table

Revision ID: 2f75e345e1ff
Revises: 9cde9e647fb0
Create Date: 2026-03-26 20:09:23.592576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f75e345e1ff'
down_revision: Union[str, Sequence[str], None] = '9cde9e647fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vn_index',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stock_id', sa.String(length=255), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('open_index_value', sa.Float(), nullable=False),
    sa.Column('highest_index_value', sa.Float(), nullable=False),
    sa.Column('lowest_index_value', sa.Float(), nullable=False),
    sa.Column('close_index_value', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vn_index_stock_id'), 'vn_index', ['stock_id'], unique=False)
    op.create_index(op.f('ix_vn_index_trading_date'), 'vn_index', ['trading_date'], unique=False)
    op.drop_index(op.f('ix_fund_gav_month'), table_name='fund_gav')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_fund_gav_month'), 'fund_gav', ['month'], unique=False)
    op.drop_index(op.f('ix_vn_index_trading_date'), table_name='vn_index')
    op.drop_index(op.f('ix_vn_index_stock_id'), table_name='vn_index')
    op.drop_table('vn_index')
    # ### end Alembic commands ###
