"""init tables

Revision ID: 3ffab288ce3c
Revises: fde6c78b19f6
Create Date: 2026-03-05 18:30:04.557658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ffab288ce3c'
down_revision: Union[str, Sequence[str], None] = 'fde6c78b19f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fund_gav',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fund_id', sa.String(length=255), nullable=False),
    sa.Column('stock_id', sa.String(length=255), nullable=False),
    sa.Column('business_sector', sa.String(length=255), nullable=False),
    sa.Column('gav', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fund_gav_business_sector'), 'fund_gav', ['business_sector'], unique=False)
    op.create_index(op.f('ix_fund_gav_fund_id'), 'fund_gav', ['fund_id'], unique=False)
    op.create_index(op.f('ix_fund_gav_stock_id'), 'fund_gav', ['stock_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fund_gav_stock_id'), table_name='fund_gav')
    op.drop_index(op.f('ix_fund_gav_fund_id'), table_name='fund_gav')
    op.drop_index(op.f('ix_fund_gav_business_sector'), table_name='fund_gav')
    op.drop_table('fund_gav')
    # ### end Alembic commands ###
