"""create newspapper table

Revision ID: 4530b882d9f8
Revises: 8cdd4b205faf
Create Date: 2026-05-16 20:25:00.632927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4530b882d9f8'
down_revision: Union[str, Sequence[str], None] = '8cdd4b205faf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('newspaper', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('newspaper', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
