"""init tables

Revision ID: 4d4209120cdc
Revises: 5f830a00e6fd
Create Date: 2026-03-12 12:07:50.665893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d4209120cdc'
down_revision: Union[str, Sequence[str], None] = '5f830a00e6fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_foreign_trade_foreign_room'), table_name='foreign_trade')
    op.drop_index(op.f('ix_foreign_trade_stock_id'), table_name='foreign_trade')
    op.drop_index(op.f('ix_foreign_trade_trading_date'), table_name='foreign_trade')
    op.drop_table('foreign_trade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foreign_trade',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('stock_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('trading_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('foreign_room', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('buy_volume', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sell_volume', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('foreign_trade_pkey'))
    )
    op.create_index(op.f('ix_foreign_trade_trading_date'), 'foreign_trade', ['trading_date'], unique=False)
    op.create_index(op.f('ix_foreign_trade_stock_id'), 'foreign_trade', ['stock_id'], unique=False)
    op.create_index(op.f('ix_foreign_trade_foreign_room'), 'foreign_trade', ['foreign_room'], unique=False)
    # ### end Alembic commands ###
