"""recreate vn index table

Revision ID: 4ebca58317a3
Revises: 3b5023d395c8
Create Date: 2026-05-14 13:34:59.194390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ebca58317a3'
down_revision: Union[str, Sequence[str], None] = '3b5023d395c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newspaper_url',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('newspaper_title', sa.String(length=255), nullable=False),
    sa.Column('newspaper_url', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('is_crawled', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newspaper_url_created_at'), 'newspaper_url', ['created_at'], unique=False)
    op.create_index(op.f('ix_newspaper_url_newspaper_title'), 'newspaper_url', ['newspaper_title'], unique=False)
    op.create_index(op.f('ix_newspaper_url_newspaper_url'), 'newspaper_url', ['newspaper_url'], unique=False)
    op.create_index(op.f('ix_newspaper_url_source'), 'newspaper_url', ['source'], unique=False)
    op.drop_index(op.f('ix_income_statement_finance_and_banking_stock_id'), table_name='income_statement_finance_and_banking')
    op.drop_table('income_statement_finance_and_banking')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income_statement_finance_and_banking',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('stock_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('quarter', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('net_interest_income', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('interest_and_similar_income', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('interest_and_simlar_expense', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('net_fee_and_commission_income', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fee_and_commission_income', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fee_and_commission_expense', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('net_gain_loss_from_foreign_exchange_business', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('net_gain_loss_from_trading_securities', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('net_gain_loss_from_investment_securities', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('net_gain_loss_from_other_activities', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('other_operating_income', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('other_operating_expenses', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('income_from_shareholding_and_capital_contribution', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('operating_expenses', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('operating_profit_before_provision_for_credit_losses', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('provision_for_credit_losses', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_profit_before_tax', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('corporate_income_tax_expense', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_corporate_income_tax_expense', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deferred_corporate_income_tax_expense', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('net_profit_after_corporate_income_tax', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('non_controlling_interests_and_preferred_dividends', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('net_profit_after_tax_attributable_to_ordinary_equity_holders', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('income_statement_finance_and_banking_pkey'))
    )
    op.create_index(op.f('ix_income_statement_finance_and_banking_stock_id'), 'income_statement_finance_and_banking', ['stock_id'], unique=False)
    op.drop_index(op.f('ix_newspaper_url_source'), table_name='newspaper_url')
    op.drop_index(op.f('ix_newspaper_url_newspaper_url'), table_name='newspaper_url')
    op.drop_index(op.f('ix_newspaper_url_newspaper_title'), table_name='newspaper_url')
    op.drop_index(op.f('ix_newspaper_url_created_at'), table_name='newspaper_url')
    op.drop_table('newspaper_url')
    # ### end Alembic commands ###
