"""create newspapper table

Revision ID: 719cc14aba33
Revises: eff379c29b5c
Create Date: 2026-05-16 20:34:30.915391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '719cc14aba33'
down_revision: Union[str, Sequence[str], None] = 'eff379c29b5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newspaper',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('newspaper_title', sa.Text(), nullable=False),
    sa.Column('newspaper_url', sa.String(length=255), nullable=False),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('newspaper_content', sa.Text(), nullable=True),
    sa.Column('newspaper_summary', sa.Text(), nullable=False),
    sa.Column('is_load_to_qrant', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('newspaper')
    # ### end Alembic commands ###
