"""create company name table

Revision ID: 87ae92482c49
Revises: f49da8091322
Create Date: 2026-02-28 09:28:05.447398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87ae92482c49'
down_revision: Union[str, Sequence[str], None] = 'f49da8091322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_name',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stock_id', sa.String(length=64), nullable=False),
    sa.Column('company_name', sa.String(length=64), nullable=False),
    sa.Column('business_sector', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_name_business_sector'), 'company_name', ['business_sector'], unique=False)
    op.create_index(op.f('ix_company_name_company_name'), 'company_name', ['company_name'], unique=False)
    op.create_index(op.f('ix_company_name_stock_id'), 'company_name', ['stock_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_name_stock_id'), table_name='company_name')
    op.drop_index(op.f('ix_company_name_company_name'), table_name='company_name')
    op.drop_index(op.f('ix_company_name_business_sector'), table_name='company_name')
    op.drop_table('company_name')
    # ### end Alembic commands ###
