"""create newspapper table

Revision ID: 9b242a567a38
Revises: 2da7bd88f3ad
Create Date: 2026-05-28 09:37:53.411173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b242a567a38'
down_revision: Union[str, Sequence[str], None] = '2da7bd88f3ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fs_cash_flow_statement_type_one', 'investing_activities_section')
    op.drop_column('fs_cash_flow_statement_type_one', 'financing_activities_section')
    op.drop_column('fs_cash_flow_statement_type_one', 'operating_activities_section')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fs_cash_flow_statement_type_one', sa.Column('operating_activities_section', sa.BIGINT(), autoincrement=False, nullable=False, comment='I. Lưu chuyển tiền từ hoạt động kinh doanh'))
    op.add_column('fs_cash_flow_statement_type_one', sa.Column('financing_activities_section', sa.BIGINT(), autoincrement=False, nullable=False, comment='III. Lưu chuyển tiền từ hoạt động tài chính'))
    op.add_column('fs_cash_flow_statement_type_one', sa.Column('investing_activities_section', sa.BIGINT(), autoincrement=False, nullable=False, comment='II. Lưu chuyển tiền từ hoạt động đầu tư'))
    # ### end Alembic commands ###
