"""create colume

Revision ID: 9cde9e647fb0
Revises: 39046d33f6a3
Create Date: 2026-03-13 16:20:55.037926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cde9e647fb0'
down_revision: Union[str, Sequence[str], None] = '39046d33f6a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fund_gav', sa.Column('month', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_fund_gav_month'), 'fund_gav', ['month'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fund_gav_month'), table_name='fund_gav')
    op.drop_column('fund_gav', 'month')
    # ### end Alembic commands ###
