"""create newspapper table

Revision ID: a82fff4fbd5a
Revises: d61bbe8a03e7
Create Date: 2026-05-16 20:28:14.134469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a82fff4fbd5a'
down_revision: Union[str, Sequence[str], None] = 'd61bbe8a03e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newspaper',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('newspaper_content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('is_embedded', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('newspaper')
    # ### end Alembic commands ###
