"""create newspapper table

Revision ID: cf1b291544a4
Revises: dcca09c179cf
Create Date: 2026-05-28 14:54:51.981830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf1b291544a4'
down_revision: Union[str, Sequence[str], None] = 'dcca09c179cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fs_financial_statistics_overview_quarter'), table_name='fs_financial_statistics_overview')
    op.drop_index(op.f('ix_fs_financial_statistics_overview_stock_id'), table_name='fs_financial_statistics_overview')
    op.drop_index(op.f('ix_fs_financial_statistics_overview_year'), table_name='fs_financial_statistics_overview')
    op.drop_table('fs_financial_statistics_overview')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fs_financial_statistics_overview',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('stock_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quarter', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('p_e', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='P/E'),
    sa.Column('p_s', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='P/S'),
    sa.Column('p_b', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='P/B'),
    sa.Column('eps', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='EPS'),
    sa.Column('net_profit_margin', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='Net Profit Margin'),
    sa.Column('yoea', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='YOE'),
    sa.Column('nim', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='NIM'),
    sa.Column('cof', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='COF'),
    sa.Column('lar', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='LAR'),
    sa.Column('ldr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='LDR'),
    sa.Column('clr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='CLR'),
    sa.Column('cta', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='CTA'),
    sa.Column('elr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='ELR'),
    sa.Column('roa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='ROA'),
    sa.Column('roe', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='ROE'),
    sa.Column('cir', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='CIR'),
    sa.Column('llrl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='LLRL'),
    sa.Column('llrnpl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='LLRNPL'),
    sa.Column('npl_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='NPL Ratio'),
    sa.Column('pcl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='PCL'),
    sa.PrimaryKeyConstraint('id', name=op.f('fs_financial_statistics_overview_pkey'))
    )
    op.create_index(op.f('ix_fs_financial_statistics_overview_year'), 'fs_financial_statistics_overview', ['year'], unique=False)
    op.create_index(op.f('ix_fs_financial_statistics_overview_stock_id'), 'fs_financial_statistics_overview', ['stock_id'], unique=False)
    op.create_index(op.f('ix_fs_financial_statistics_overview_quarter'), 'fs_financial_statistics_overview', ['quarter'], unique=False)
    # ### end Alembic commands ###
