"""create newspapper table

Revision ID: d1c847d4aed9
Revises: 2a6c341622d7
Create Date: 2026-05-16 20:30:01.889236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1c847d4aed9'
down_revision: Union[str, Sequence[str], None] = '2a6c341622d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newspaper',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('newspaper_title', sa.Text(), nullable=False),
    sa.Column('newspaper_url', sa.String(length=255), nullable=False),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('newspaper_content', sa.Text(), nullable=True),
    sa.Column('newspaper_summary', sa.Text(), nullable=False),
    sa.Column('is_embedded', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('newspaper')
    # ### end Alembic commands ###
